version: 2
updates:
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    coverlet:
      patterns:
      - coverlet.*
  cooldown:
    default-days: 7
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
