{
  "swagger": "2.0",
  "info": {
    "title": "OData Service for namespace microsoft.graph",
    "description": "This OData service is located at https://graph.microsoft.com/v1.0",
    "version": "1.0.1"
  },
  "host": "graph.microsoft.com",
  "basePath": "/v1.0",
  "schemes": [
    "https"
  ],
  "paths": {
    "/contracts": {
      "get": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Get entities from contracts",
        "operationId": "contracts.contract.ListContract",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Add new entity to contracts",
        "operationId": "contracts.contract.CreateContract"
      }
    },
    "/contracts({contract-id})": {
      "get": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Get entity from contracts by key",
        "operationId": "contracts.contract.GetContract",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Update entity in contracts",
        "operationId": "contracts.contract.UpdateContract"
      },
      "delete": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Delete entity from contracts",
        "operationId": "contracts.contract.DeleteContract"
      }
    },
    "/devices": {
      "get": {
        "tags": [
          "devices.device"
        ],
        "summary": "Get entities from devices",
        "operationId": "devices.device.ListDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Device.ReadWrite.All",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "devices.device"
        ],
        "summary": "Add new entity to devices",
        "operationId": "devices.device.CreateDevice"
      }
    },
    "/devices({device-id})": {
      "get": {
        "tags": [
          "devices.device"
        ],
        "summary": "Get entity from devices by key",
        "operationId": "devices.device.GetDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Device.ReadWrite.All",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "devices.device"
        ],
        "summary": "Update entity in devices",
        "operationId": "devices.device.UpdateDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "devices.device"
        ],
        "summary": "Delete entity from devices",
        "operationId": "devices.device.DeleteDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/devices({device-id})/extensions": {
      "get": {
        "tags": [
          "devices.extension"
        ],
        "summary": "Get extensions from devices",
        "operationId": "devices.ListExtensions"
      }
    },
    "/devices({device-id})/extensions({extension-id})": {
      "get": {
        "tags": [
          "devices.extension"
        ],
        "summary": "Get extensions from devices",
        "operationId": "devices.GetExtensions"
      }
    },
    "/devices({device-id})/registeredOwners": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredOwners from devices",
        "operationId": "devices.ListRegisteredOwners"
      }
    },
    "/devices({device-id})/registeredOwners({directoryObject-id})": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredOwners from devices",
        "operationId": "devices.GetRegisteredOwners"
      }
    },
    "/devices({device-id})/registeredUsers": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredUsers from devices",
        "operationId": "devices.ListRegisteredUsers"
      }
    },
    "/devices({device-id})/registeredUsers({directoryObject-id})": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredUsers from devices",
        "operationId": "devices.GetRegisteredUsers"
      }
    },
    "/directoryObjects": {
      "get": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Get entities from directoryObjects",
        "operationId": "directoryObjects.directoryObject.ListDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Add new entity to directoryObjects",
        "operationId": "directoryObjects.directoryObject.CreateDirectoryObject"
      }
    },
    "/directoryObjects({directoryObject-id})": {
      "get": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Get entity from directoryObjects by key",
        "operationId": "directoryObjects.directoryObject.GetDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Update entity in directoryObjects",
        "operationId": "directoryObjects.directoryObject.UpdateDirectoryObject"
      },
      "delete": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Delete entity from directoryObjects",
        "operationId": "directoryObjects.directoryObject.DeleteDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/directoryRoles": {
      "get": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Get entities from directoryRoles",
        "operationId": "directoryRoles.directoryRole.ListDirectoryRole",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Add new entity to directoryRoles",
        "operationId": "directoryRoles.directoryRole.CreateDirectoryRole"
      }
    },
    "/directoryRoles({directoryRole-id})": {
      "get": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Get entity from directoryRoles by key",
        "operationId": "directoryRoles.directoryRole.GetDirectoryRole",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Update entity in directoryRoles",
        "operationId": "directoryRoles.directoryRole.UpdateDirectoryRole"
      },
      "delete": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Delete entity from directoryRoles",
        "operationId": "directoryRoles.directoryRole.DeleteDirectoryRole"
      }
    },
    "/directoryRoles({directoryRole-id})/members": {
      "get": {
        "tags": [
          "directoryRoles.directoryObject"
        ],
        "summary": "Get members from directoryRoles",
        "operationId": "directoryRoles.ListMembers"
      }
    },
    "/directoryRoles({directoryRole-id})/members({directoryObject-id})": {
      "get": {
        "tags": [
          "directoryRoles.directoryObject"
        ],
        "summary": "Get members from directoryRoles",
        "operationId": "directoryRoles.GetMembers"
      }
    },
    "/directoryRoleTemplates": {
      "get": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Get entities from directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.ListDirectoryRoleTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Add new entity to directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.CreateDirectoryRoleTemplate"
      }
    },
    "/directoryRoleTemplates({directoryRoleTemplate-id})": {
      "get": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Get entity from directoryRoleTemplates by key",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.GetDirectoryRoleTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Update entity in directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.UpdateDirectoryRoleTemplate"
      },
      "delete": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Delete entity from directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.DeleteDirectoryRoleTemplate"
      }
    },
    "/domains": {
      "get": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Get entities from domains",
        "operationId": "domains.domain.ListDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Add new entity to domains",
        "operationId": "domains.domain.CreateDomain"
      }
    },
    "/domains({domain-id})": {
      "get": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Get entity from domains by key",
        "operationId": "domains.domain.GetDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Update entity in domains",
        "operationId": "domains.domain.UpdateDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Delete entity from domains",
        "operationId": "domains.domain.DeleteDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Domain.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/domains({domain-id})/domainNameReferences": {
      "get": {
        "tags": [
          "domains.directoryObject"
        ],
        "summary": "Get domainNameReferences from domains",
        "operationId": "domains.ListDomainNameReferences"
      }
    },
    "/domains({domain-id})/domainNameReferences({directoryObject-id})": {
      "get": {
        "tags": [
          "domains.directoryObject"
        ],
        "summary": "Get domainNameReferences from domains",
        "operationId": "domains.GetDomainNameReferences"
      }
    },
    "/domains({domain-id})/serviceConfigurationRecords": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get serviceConfigurationRecords from domains",
        "operationId": "domains.ListServiceConfigurationRecords"
      }
    },
    "/domains({domain-id})/serviceConfigurationRecords({domainDnsRecord-id})": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get serviceConfigurationRecords from domains",
        "operationId": "domains.GetServiceConfigurationRecords"
      }
    },
    "/domains({domain-id})/verificationDnsRecords": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get verificationDnsRecords from domains",
        "operationId": "domains.ListVerificationDnsRecords"
      }
    },
    "/domains({domain-id})/verificationDnsRecords({domainDnsRecord-id})": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get verificationDnsRecords from domains",
        "operationId": "domains.GetVerificationDnsRecords"
      }
    },
    "/drives": {
      "get": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Get entities from drives",
        "operationId": "drives.drive.ListDrive"
      },
      "post": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Add new entity to drives",
        "operationId": "drives.drive.CreateDrive"
      }
    },
    "/drives({drive-id})": {
      "get": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Get entity from drives by key",
        "operationId": "drives.drive.GetDrive"
      },
      "patch": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Update entity in drives",
        "operationId": "drives.drive.UpdateDrive"
      },
      "delete": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Delete entity from drives",
        "operationId": "drives.drive.DeleteDrive"
      }
    },
    "/drives({drive-id})/items": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get items from drives",
        "operationId": "drives.ListItems"
      }
    },
    "/drives({drive-id})/items({driveItem-id})": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get items from drives",
        "operationId": "drives.GetItems"
      }
    },
    "/drives({drive-id})/root": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get root from drives",
        "operationId": "drives.GetRoot"
      }
    },
    "/drives({drive-id})/special": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get special from drives",
        "operationId": "drives.ListSpecial"
      }
    },
    "/drives({drive-id})/special({driveItem-id})": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get special from drives",
        "operationId": "drives.GetSpecial"
      }
    },
    "/drives({drive-id})/list": {
      "get": {
        "tags": [
          "drives.list"
        ],
        "summary": "Get list from drives",
        "operationId": "drives.GetList"
      }
    },
    "/groupLifecyclePolicies": {
      "get": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Get entities from groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.ListGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Add new entity to groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.CreateGroupLifecyclePolicy"
      }
    },
    "/groupLifecyclePolicies({groupLifecyclePolicy-id})": {
      "get": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Get entity from groupLifecyclePolicies by key",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.GetGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Update entity in groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.UpdateGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Delete entity from groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.DeleteGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups": {
      "get": {
        "tags": [
          "groups.group"
        ],
        "summary": "Get entities from groups",
        "operationId": "groups.group.ListGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groups.group"
        ],
        "summary": "Add new entity to groups",
        "operationId": "groups.group.CreateGroup"
      }
    },
    "/groups({group-id})": {
      "get": {
        "tags": [
          "groups.group"
        ],
        "summary": "Get entity from groups by key",
        "operationId": "groups.group.GetGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groups.group"
        ],
        "summary": "Update entity in groups",
        "operationId": "groups.group.UpdateGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groups.group"
        ],
        "summary": "Delete entity from groups",
        "operationId": "groups.group.DeleteGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups({group-id})/acceptedSenders": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get acceptedSenders from groups",
        "operationId": "groups.ListAcceptedSenders"
      }
    },
    "/groups({group-id})/acceptedSenders({directoryObject-id})": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get acceptedSenders from groups",
        "operationId": "groups.GetAcceptedSenders"
      }
    },
    "/groups({group-id})/calendar": {
      "get": {
        "tags": [
          "groups.calendar"
        ],
        "summary": "Get calendar from groups",
        "operationId": "groups.GetCalendar"
      }
    },
    "/groups({group-id})/calendarView": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get calendarView from groups",
        "operationId": "groups.ListCalendarView"
      }
    },
    "/groups({group-id})/calendarView({event-id})": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get calendarView from groups",
        "operationId": "groups.GetCalendarView"
      }
    },
    "/groups({group-id})/conversations": {
      "get": {
        "tags": [
          "groups.conversation"
        ],
        "summary": "Get conversations from groups",
        "operationId": "groups.ListConversations"
      }
    },
    "/groups({group-id})/conversations({conversation-id})": {
      "get": {
        "tags": [
          "groups.conversation"
        ],
        "summary": "Get conversations from groups",
        "operationId": "groups.GetConversations"
      }
    },
    "/groups({group-id})/createdOnBehalfOf": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get createdOnBehalfOf from groups",
        "operationId": "groups.GetCreatedOnBehalfOf"
      }
    },
    "/groups({group-id})/drive": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drive from groups",
        "operationId": "groups.GetDrive"
      }
    },
    "/groups({group-id})/events": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get events from groups",
        "operationId": "groups.ListEvents"
      }
    },
    "/groups({group-id})/events({event-id})": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get events from groups",
        "operationId": "groups.GetEvents"
      }
    },
    "/groups({group-id})/memberOf": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get memberOf from groups",
        "operationId": "groups.ListMemberOf"
      }
    },
    "/groups({group-id})/memberOf({directoryObject-id})": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get memberOf from groups",
        "operationId": "groups.GetMemberOf"
      }
    },
    "/groups({group-id})/members": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get members from groups",
        "operationId": "groups.ListMembers"
      }
    },
    "/groups({group-id})/members({directoryObject-id})": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get members from groups",
        "operationId": "groups.GetMembers"
      }
    },
    "/groups({group-id})/owners": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get owners from groups",
        "operationId": "groups.ListOwners"
      }
    },
    "/groups({group-id})/owners({directoryObject-id})": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get owners from groups",
        "operationId": "groups.GetOwners"
      }
    },
    "/groups({group-id})/photo": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photo from groups",
        "operationId": "groups.GetPhoto"
      }
    },
    "/groups({group-id})/rejectedSenders": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get rejectedSenders from groups",
        "operationId": "groups.ListRejectedSenders"
      }
    },
    "/groups({group-id})/rejectedSenders({directoryObject-id})": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get rejectedSenders from groups",
        "operationId": "groups.GetRejectedSenders"
      }
    },
    "/groups({group-id})/sites": {
      "get": {
        "tags": [
          "groups.site"
        ],
        "summary": "Get sites from groups",
        "operationId": "groups.ListSites"
      }
    },
    "/groups({group-id})/sites({site-id})": {
      "get": {
        "tags": [
          "groups.site"
        ],
        "summary": "Get sites from groups",
        "operationId": "groups.GetSites"
      }
    },
    "/groups({group-id})/threads": {
      "get": {
        "tags": [
          "groups.conversationThread"
        ],
        "summary": "Get threads from groups",
        "operationId": "groups.ListThreads"
      }
    },
    "/groups({group-id})/threads({conversationThread-id})": {
      "get": {
        "tags": [
          "groups.conversationThread"
        ],
        "summary": "Get threads from groups",
        "operationId": "groups.GetThreads"
      }
    },
    "/groups({group-id})/drives": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drives from groups",
        "operationId": "groups.ListDrives"
      }
    },
    "/groups({group-id})/drives({drive-id})": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drives from groups",
        "operationId": "groups.GetDrives"
      }
    },
    "/groups({group-id})/extensions": {
      "get": {
        "tags": [
          "groups.extension"
        ],
        "summary": "Get extensions from groups",
        "operationId": "groups.ListExtensions"
      }
    },
    "/groups({group-id})/extensions({extension-id})": {
      "get": {
        "tags": [
          "groups.extension"
        ],
        "summary": "Get extensions from groups",
        "operationId": "groups.GetExtensions"
      }
    },
    "/groups({group-id})/groupLifecyclePolicies": {
      "get": {
        "tags": [
          "groups.groupLifecyclePolicy"
        ],
        "summary": "Get groupLifecyclePolicies from groups",
        "operationId": "groups.ListGroupLifecyclePolicies"
      }
    },
    "/groups({group-id})/groupLifecyclePolicies({groupLifecyclePolicy-id})": {
      "get": {
        "tags": [
          "groups.groupLifecyclePolicy"
        ],
        "summary": "Get groupLifecyclePolicies from groups",
        "operationId": "groups.GetGroupLifecyclePolicies"
      }
    },
    "/groups({group-id})/onenote": {
      "get": {
        "tags": [
          "groups.onenote"
        ],
        "summary": "Get onenote from groups",
        "operationId": "groups.GetOnenote"
      }
    },
    "/groups({group-id})/photos": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photos from groups",
        "operationId": "groups.ListPhotos"
      }
    },
    "/groups({group-id})/photos({profilePhoto-id})": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photos from groups",
        "operationId": "groups.GetPhotos"
      }
    },
    "/groups({group-id})/planner": {
      "get": {
        "tags": [
          "groups.plannerGroup"
        ],
        "summary": "Get planner from groups",
        "operationId": "groups.GetPlanner"
      }
    },
    "/groups({group-id})/settings": {
      "get": {
        "tags": [
          "groups.groupSetting"
        ],
        "summary": "Get settings from groups",
        "operationId": "groups.ListSettings"
      }
    },
    "/groups({group-id})/settings({groupSetting-id})": {
      "get": {
        "tags": [
          "groups.groupSetting"
        ],
        "summary": "Get settings from groups",
        "operationId": "groups.GetSettings"
      }
    },
    "/groupSettings": {
      "get": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Get entities from groupSettings",
        "operationId": "groupSettings.groupSetting.ListGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Add new entity to groupSettings",
        "operationId": "groupSettings.groupSetting.CreateGroupSetting"
      }
    },
    "/groupSettings({groupSetting-id})": {
      "get": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Get entity from groupSettings by key",
        "operationId": "groupSettings.groupSetting.GetGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Update entity in groupSettings",
        "operationId": "groupSettings.groupSetting.UpdateGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Delete entity from groupSettings",
        "operationId": "groupSettings.groupSetting.DeleteGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groupSettingTemplates": {
      "get": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Get entities from groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.ListGroupSettingTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Add new entity to groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.CreateGroupSettingTemplate"
      }
    },
    "/groupSettingTemplates({groupSettingTemplate-id})": {
      "get": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Get entity from groupSettingTemplates by key",
        "operationId": "groupSettingTemplates.groupSettingTemplate.GetGroupSettingTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Update entity in groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.UpdateGroupSettingTemplate"
      },
      "delete": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Delete entity from groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.DeleteGroupSettingTemplate"
      }
    },
    "/schemaExtensions": {
      "get": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Get entities from schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.ListSchemaExtension"
      },
      "post": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Add new entity to schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.CreateSchemaExtension"
      }
    },
    "/schemaExtensions({schemaExtension-id})": {
      "get": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Get entity from schemaExtensions by key",
        "operationId": "schemaExtensions.schemaExtension.GetSchemaExtension"
      },
      "patch": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Update entity in schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.UpdateSchemaExtension",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Delete entity from schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.DeleteSchemaExtension",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/shares": {
      "get": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Get entities from shares",
        "operationId": "shares.sharedDriveItem.ListSharedDriveItem",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Add new entity to shares",
        "operationId": "shares.sharedDriveItem.CreateSharedDriveItem"
      }
    },
    "/shares({sharedDriveItem-id})": {
      "get": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Get entity from shares by key",
        "operationId": "shares.sharedDriveItem.GetSharedDriveItem",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Update entity in shares",
        "operationId": "shares.sharedDriveItem.UpdateSharedDriveItem"
      },
      "delete": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Delete entity from shares",
        "operationId": "shares.sharedDriveItem.DeleteSharedDriveItem"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get driveItem from shares",
        "operationId": "shares.GetDriveItem"
      }
    },
    "/shares({sharedDriveItem-id})/items": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get items from shares",
        "operationId": "shares.ListItems"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get items from shares",
        "operationId": "shares.GetItems"
      }
    },
    "/shares({sharedDriveItem-id})/list": {
      "get": {
        "tags": [
          "shares.list"
        ],
        "summary": "Get list from shares",
        "operationId": "shares.GetList"
      }
    },
    "/shares({sharedDriveItem-id})/listItem": {
      "get": {
        "tags": [
          "shares.listItem"
        ],
        "summary": "Get listItem from shares",
        "operationId": "shares.GetListItem"
      }
    },
    "/shares({sharedDriveItem-id})/root": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get root from shares",
        "operationId": "shares.GetRoot"
      }
    },
    "/shares({sharedDriveItem-id})/site": {
      "get": {
        "tags": [
          "shares.site"
        ],
        "summary": "Get site from shares",
        "operationId": "shares.GetSite"
      }
    },
    "/sites": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get entities from sites",
        "operationId": "sites.site.ListSite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "sites.site"
        ],
        "summary": "Add new entity to sites",
        "operationId": "sites.site.CreateSite"
      }
    },
    "/sites({site-id})": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get entity from sites by key",
        "operationId": "sites.site.GetSite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "sites.site"
        ],
        "summary": "Update entity in sites",
        "operationId": "sites.site.UpdateSite"
      },
      "delete": {
        "tags": [
          "sites.site"
        ],
        "summary": "Delete entity from sites",
        "operationId": "sites.site.DeleteSite"
      }
    },
    "/sites({site-id})/contentTypes": {
      "get": {
        "tags": [
          "sites.contentType"
        ],
        "summary": "Get contentTypes from sites",
        "operationId": "sites.ListContentTypes"
      }
    },
    "/sites({site-id})/contentTypes({contentType-id})": {
      "get": {
        "tags": [
          "sites.contentType"
        ],
        "summary": "Get contentTypes from sites",
        "operationId": "sites.GetContentTypes"
      }
    },
    "/sites({site-id})/drive": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drive from sites",
        "operationId": "sites.GetDrive"
      }
    },
    "/sites({site-id})/drives": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drives from sites",
        "operationId": "sites.ListDrives"
      }
    },
    "/sites({site-id})/drives({drive-id})": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drives from sites",
        "operationId": "sites.GetDrives"
      }
    },
    "/sites({site-id})/items": {
      "get": {
        "tags": [
          "sites.baseItem"
        ],
        "summary": "Get items from sites",
        "operationId": "sites.ListItems"
      }
    },
    "/sites({site-id})/items({baseItem-id})": {
      "get": {
        "tags": [
          "sites.baseItem"
        ],
        "summary": "Get items from sites",
        "operationId": "sites.GetItems"
      }
    },
    "/sites({site-id})/lists": {
      "get": {
        "tags": [
          "sites.list"
        ],
        "summary": "Get lists from sites",
        "operationId": "sites.ListLists"
      }
    },
    "/sites({site-id})/lists({list-id})": {
      "get": {
        "tags": [
          "sites.list"
        ],
        "summary": "Get lists from sites",
        "operationId": "sites.GetLists"
      }
    },
    "/sites({site-id})/sites": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get sites from sites",
        "operationId": "sites.ListSites"
      }
    },
    "/sites({site-id})/sites({site-id})": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get sites from sites",
        "operationId": "sites.GetSites"
      }
    },
    "/sites({site-id})/columns": {
      "get": {
        "tags": [
          "sites.columnDefinition"
        ],
        "summary": "Get columns from sites",
        "operationId": "sites.ListColumns"
      }
    },
    "/sites({site-id})/columns({columnDefinition-id})": {
      "get": {
        "tags": [
          "sites.columnDefinition"
        ],
        "summary": "Get columns from sites",
        "operationId": "sites.GetColumns"
      }
    },
    "/sites({site-id})/onenote": {
      "get": {
        "tags": [
          "sites.onenote"
        ],
        "summary": "Get onenote from sites",
        "operationId": "sites.GetOnenote"
      }
    },
    "/subscribedSkus": {
      "get": {
        "tags": [
          "subscribedSkus.subscribedSku"
        ],
        "summary": "Get entities from subscribedSkus",
        "operationId": "subscribedSkus.subscribedSku.ListSubscribedSku",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "subscribedSkus.subscribedSku"
        ],
        "summary": "Add new entity to subscribedSkus",
        "operationId": "subscribedSkus.subscribedSku.CreateSubscribedSku"
      }
    },
    "/subscribedSkus({subscribedSku-id})": {
      "get": {
        "tags": [
          "subscribedSkus.subscribedSku"
        ],
        "summary": "Get entity from subscribedSkus by key",
        "operationId": "subscribedSkus.subscribedSku.GetSubscribedSku",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "subscribedSkus.subscribedSku"
        ],
        "summary": "Update entity in subscribedSkus",
        "operationId": "subscribedSkus.subscribedSku.UpdateSubscribedSku"
      },
      "delete": {
        "tags": [
          "subscribedSkus.subscribedSku"
        ],
        "summary": "Delete entity from subscribedSkus",
        "operationId": "subscribedSkus.subscribedSku.DeleteSubscribedSku"
      }
    },
    "/subscriptions": {
      "get": {
        "tags": [
          "subscriptions.subscription"
        ],
        "summary": "Get entities from subscriptions",
        "operationId": "subscriptions.subscription.ListSubscription"
      },
      "post": {
        "tags": [
          "subscriptions.subscription"
        ],
        "summary": "Add new entity to subscriptions",
        "operationId": "subscriptions.subscription.CreateSubscription"
      }
    },
    "/subscriptions({subscription-id})": {
      "get": {
        "tags": [
          "subscriptions.subscription"
        ],
        "summary": "Get entity from subscriptions by key",
        "operationId": "subscriptions.subscription.GetSubscription"
      },
      "patch": {
        "tags": [
          "subscriptions.subscription"
        ],
        "summary": "Update entity in subscriptions",
        "operationId": "subscriptions.subscription.UpdateSubscription"
      },
      "delete": {
        "tags": [
          "subscriptions.subscription"
        ],
        "summary": "Delete entity from subscriptions",
        "operationId": "subscriptions.subscription.DeleteSubscription"
      }
    },
    "/users": {
      "get": {
        "tags": [
          "users.user"
        ],
        "summary": "Get entities from users",
        "operationId": "users.user.ListUser"
      },
      "post": {
        "tags": [
          "users.user"
        ],
        "summary": "Add new entity to users",
        "operationId": "users.user.CreateUser"
      }
    },
    "/users({user-id})": {
      "get": {
        "tags": [
          "users.user"
        ],
        "summary": "Get entity from users by key",
        "operationId": "users.user.GetUser"
      },
      "patch": {
        "tags": [
          "users.user"
        ],
        "summary": "Update entity in users",
        "operationId": "users.user.UpdateUser"
      },
      "delete": {
        "tags": [
          "users.user"
        ],
        "summary": "Delete entity from users",
        "operationId": "users.user.DeleteUser",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "User.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/users({user-id})/managedDevices": {
      "get": {
        "tags": [
          "users.managedDevice"
        ],
        "summary": "Get managedDevices from users",
        "operationId": "users.ListManagedDevices"
      }
    },
    "/users({user-id})/managedDevices({managedDevice-id})": {
      "get": {
        "tags": [
          "users.managedDevice"
        ],
        "summary": "Get managedDevices from users",
        "operationId": "users.GetManagedDevices"
      }
    },
    "/users({user-id})/managedAppRegistrations": {
      "get": {
        "tags": [
          "users.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from users",
        "operationId": "users.ListManagedAppRegistrations"
      }
    },
    "/users({user-id})/managedAppRegistrations({managedAppRegistration-id})": {
      "get": {
        "tags": [
          "users.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from users",
        "operationId": "users.GetManagedAppRegistrations"
      }
    },
    "/users({user-id})/deviceManagementTroubleshootingEvents": {
      "get": {
        "tags": [
          "users.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from users",
        "operationId": "users.ListDeviceManagementTroubleshootingEvents"
      }
    },
    "/users({user-id})/deviceManagementTroubleshootingEvents({deviceManagementTroubleshootingEvent-id})": {
      "get": {
        "tags": [
          "users.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from users",
        "operationId": "users.GetDeviceManagementTroubleshootingEvents"
      }
    },
    "/users({user-id})/calendar": {
      "get": {
        "tags": [
          "users.calendar"
        ],
        "summary": "Get calendar from users",
        "operationId": "users.GetCalendar"
      }
    },
    "/users({user-id})/calendarGroups": {
      "get": {
        "tags": [
          "users.calendarGroup"
        ],
        "summary": "Get calendarGroups from users",
        "operationId": "users.ListCalendarGroups"
      }
    },
    "/users({user-id})/calendarGroups({calendarGroup-id})": {
      "get": {
        "tags": [
          "users.calendarGroup"
        ],
        "summary": "Get calendarGroups from users",
        "operationId": "users.GetCalendarGroups"
      }
    },
    "/users({user-id})/calendarView": {
      "get": {
        "tags": [
          "users.event"
        ],
        "summary": "Get calendarView from users",
        "operationId": "users.ListCalendarView"
      }
    },
    "/users({user-id})/calendarView({event-id})": {
      "get": {
        "tags": [
          "users.event"
        ],
        "summary": "Get calendarView from users",
        "operationId": "users.GetCalendarView"
      }
    },
    "/users({user-id})/calendars": {
      "get": {
        "tags": [
          "users.calendar"
        ],
        "summary": "Get calendars from users",
        "operationId": "users.ListCalendars"
      }
    },
    "/users({user-id})/calendars({calendar-id})": {
      "get": {
        "tags": [
          "users.calendar"
        ],
        "summary": "Get calendars from users",
        "operationId": "users.GetCalendars"
      }
    },
    "/users({user-id})/contacts": {
      "get": {
        "tags": [
          "users.contact"
        ],
        "summary": "Get contacts from users",
        "operationId": "users.ListContacts"
      }
    },
    "/users({user-id})/contacts({contact-id})": {
      "get": {
        "tags": [
          "users.contact"
        ],
        "summary": "Get contacts from users",
        "operationId": "users.GetContacts"
      }
    },
    "/users({user-id})/contactFolders": {
      "get": {
        "tags": [
          "users.contactFolder"
        ],
        "summary": "Get contactFolders from users",
        "operationId": "users.ListContactFolders"
      }
    },
    "/users({user-id})/contactFolders({contactFolder-id})": {
      "get": {
        "tags": [
          "users.contactFolder"
        ],
        "summary": "Get contactFolders from users",
        "operationId": "users.GetContactFolders"
      }
    },
    "/users({user-id})/createdObjects": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get createdObjects from users",
        "operationId": "users.ListCreatedObjects"
      }
    },
    "/users({user-id})/createdObjects({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get createdObjects from users",
        "operationId": "users.GetCreatedObjects"
      }
    },
    "/users({user-id})/directReports": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get directReports from users",
        "operationId": "users.ListDirectReports"
      }
    },
    "/users({user-id})/directReports({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get directReports from users",
        "operationId": "users.GetDirectReports"
      }
    },
    "/users({user-id})/drive": {
      "get": {
        "tags": [
          "users.drive"
        ],
        "summary": "Get drive from users",
        "operationId": "users.GetDrive"
      }
    },
    "/users({user-id})/drives": {
      "get": {
        "tags": [
          "users.drive"
        ],
        "summary": "Get drives from users",
        "operationId": "users.ListDrives"
      }
    },
    "/users({user-id})/drives({drive-id})": {
      "get": {
        "tags": [
          "users.drive"
        ],
        "summary": "Get drives from users",
        "operationId": "users.GetDrives"
      }
    },
    "/users({user-id})/events": {
      "get": {
        "tags": [
          "users.event"
        ],
        "summary": "Get events from users",
        "operationId": "users.ListEvents"
      }
    },
    "/users({user-id})/events({event-id})": {
      "get": {
        "tags": [
          "users.event"
        ],
        "summary": "Get events from users",
        "operationId": "users.GetEvents"
      }
    },
    "/users({user-id})/inferenceClassification": {
      "get": {
        "tags": [
          "users.inferenceClassification"
        ],
        "summary": "Get inferenceClassification from users",
        "operationId": "users.GetInferenceClassification"
      }
    },
    "/users({user-id})/mailFolders": {
      "get": {
        "tags": [
          "users.mailFolder"
        ],
        "summary": "Get mailFolders from users",
        "operationId": "users.ListMailFolders"
      }
    },
    "/users({user-id})/mailFolders({mailFolder-id})": {
      "get": {
        "tags": [
          "users.mailFolder"
        ],
        "summary": "Get mailFolders from users",
        "operationId": "users.GetMailFolders"
      }
    },
    "/users({user-id})/manager": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get manager from users",
        "operationId": "users.GetManager"
      }
    },
    "/users({user-id})/memberOf": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get memberOf from users",
        "operationId": "users.ListMemberOf"
      }
    },
    "/users({user-id})/memberOf({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get memberOf from users",
        "operationId": "users.GetMemberOf"
      }
    },
    "/users({user-id})/messages": {
      "get": {
        "tags": [
          "users.message"
        ],
        "summary": "Get messages from users",
        "operationId": "users.ListMessages"
      }
    },
    "/users({user-id})/messages({message-id})": {
      "get": {
        "tags": [
          "users.message"
        ],
        "summary": "Get messages from users",
        "operationId": "users.GetMessages"
      }
    },
    "/users({user-id})/outlook": {
      "get": {
        "tags": [
          "users.outlookUser"
        ],
        "summary": "Get outlook from users",
        "operationId": "users.GetOutlook"
      }
    },
    "/users({user-id})/ownedDevices": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get ownedDevices from users",
        "operationId": "users.ListOwnedDevices"
      }
    },
    "/users({user-id})/ownedDevices({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get ownedDevices from users",
        "operationId": "users.GetOwnedDevices"
      }
    },
    "/users({user-id})/ownedObjects": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get ownedObjects from users",
        "operationId": "users.ListOwnedObjects"
      }
    },
    "/users({user-id})/ownedObjects({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get ownedObjects from users",
        "operationId": "users.GetOwnedObjects"
      }
    },
    "/users({user-id})/photo": {
      "get": {
        "tags": [
          "users.profilePhoto"
        ],
        "summary": "Get photo from users",
        "operationId": "users.GetPhoto"
      }
    },
    "/users({user-id})/registeredDevices": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get registeredDevices from users",
        "operationId": "users.ListRegisteredDevices"
      }
    },
    "/users({user-id})/registeredDevices({directoryObject-id})": {
      "get": {
        "tags": [
          "users.directoryObject"
        ],
        "summary": "Get registeredDevices from users",
        "operationId": "users.GetRegisteredDevices"
      }
    },
    "/users({user-id})/activities": {
      "get": {
        "tags": [
          "users.userActivity"
        ],
        "summary": "Get activities from users",
        "operationId": "users.ListActivities"
      }
    },
    "/users({user-id})/activities({userActivity-id})": {
      "get": {
        "tags": [
          "users.userActivity"
        ],
        "summary": "Get activities from users",
        "operationId": "users.GetActivities"
      }
    },
    "/users({user-id})/extensions": {
      "get": {
        "tags": [
          "users.extension"
        ],
        "summary": "Get extensions from users",
        "operationId": "users.ListExtensions"
      }
    },
    "/users({user-id})/extensions({extension-id})": {
      "get": {
        "tags": [
          "users.extension"
        ],
        "summary": "Get extensions from users",
        "operationId": "users.GetExtensions"
      }
    },
    "/users({user-id})/licenseDetails": {
      "get": {
        "tags": [
          "users.licenseDetails"
        ],
        "summary": "Get licenseDetails from users",
        "operationId": "users.ListLicenseDetails"
      }
    },
    "/users({user-id})/licenseDetails({licenseDetails-id})": {
      "get": {
        "tags": [
          "users.licenseDetails"
        ],
        "summary": "Get licenseDetails from users",
        "operationId": "users.GetLicenseDetails"
      }
    },
    "/users({user-id})/onenote": {
      "get": {
        "tags": [
          "users.onenote"
        ],
        "summary": "Get onenote from users",
        "operationId": "users.GetOnenote"
      }
    },
    "/users({user-id})/people": {
      "get": {
        "tags": [
          "users.person"
        ],
        "summary": "Get people from users",
        "operationId": "users.ListPeople"
      }
    },
    "/users({user-id})/people({person-id})": {
      "get": {
        "tags": [
          "users.person"
        ],
        "summary": "Get people from users",
        "operationId": "users.GetPeople"
      }
    },
    "/users({user-id})/planner": {
      "get": {
        "tags": [
          "users.plannerUser"
        ],
        "summary": "Get planner from users",
        "operationId": "users.GetPlanner"
      }
    },
    "/directory": {
      "get": {
        "tags": [
          "directory.directory"
        ],
        "summary": "Get directory",
        "operationId": "directory.directory.GetDirectory"
      },
      "patch": {
        "tags": [
          "directory.directory"
        ],
        "summary": "Update directory",
        "operationId": "directory.directory.UpdateDirectory"
      }
    },
    "/directory/deletedItems": {
      "get": {
        "tags": [
          "directory.directoryObject"
        ],
        "summary": "Get deletedItems from directory",
        "operationId": "directory.ListDeletedItems"
      }
    },
    "/directory/deletedItems({directoryObject-id})": {
      "get": {
        "tags": [
          "directory.directoryObject"
        ],
        "summary": "Get deletedItems from directory",
        "operationId": "directory.GetDeletedItems"
      }
    },
    "/education": {
      "get": {
        "tags": [
          "education.educationRoot"
        ],
        "summary": "Here is a JSON representation of the resource.",
        "operationId": "education.educationRoot.GetEducationRoot"
      },
      "patch": {
        "tags": [
          "education.educationRoot"
        ],
        "summary": "Update education",
        "operationId": "education.educationRoot.UpdateEducationRoot"
      }
    },
    "/education/classes": {
      "get": {
        "tags": [
          "education.educationClass"
        ],
        "summary": "Get classes from education",
        "operationId": "education.ListClasses"
      }
    },
    "/education/classes({educationClass-id})": {
      "get": {
        "tags": [
          "education.educationClass"
        ],
        "summary": "Get classes from education",
        "operationId": "education.GetClasses"
      }
    },
    "/education/me": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get me from education",
        "operationId": "education.GetMe"
      }
    },
    "/education/schools": {
      "get": {
        "tags": [
          "education.educationSchool"
        ],
        "summary": "Get schools from education",
        "operationId": "education.ListSchools"
      }
    },
    "/education/schools({educationSchool-id})": {
      "get": {
        "tags": [
          "education.educationSchool"
        ],
        "summary": "Get schools from education",
        "operationId": "education.GetSchools"
      }
    },
    "/education/users": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get users from education",
        "operationId": "education.ListUsers"
      }
    },
    "/education/users({educationUser-id})": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get users from education",
        "operationId": "education.GetUsers"
      }
    },
    "/invitations": {
      "get": {
        "tags": [
          "invitations.invitation"
        ],
        "summary": "Get invitations",
        "operationId": "invitations.invitation.GetInvitation"
      },
      "patch": {
        "tags": [
          "invitations.invitation"
        ],
        "summary": "Update invitations",
        "operationId": "invitations.invitation.UpdateInvitation"
      }
    },
    "/invitations/invitedUser": {
      "get": {
        "tags": [
          "invitations.user"
        ],
        "summary": "Get invitedUser from invitations",
        "operationId": "invitations.GetInvitedUser"
      }
    },
    "/me": {
      "get": {
        "tags": [
          "me.user"
        ],
        "summary": "Get me",
        "operationId": "me.user.GetUser"
      },
      "patch": {
        "tags": [
          "me.user"
        ],
        "summary": "Update me",
        "operationId": "me.user.UpdateUser",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.ReadWrite",
              "User.ReadWrite.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "User.ReadWrite"
            ]
          },
          {
            "Application": [
              "User.ReadWrite.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/me/managedDevices": {
      "get": {
        "tags": [
          "me.managedDevice"
        ],
        "summary": "Get managedDevices from me",
        "operationId": "me.ListManagedDevices"
      }
    },
    "/me/managedDevices({managedDevice-id})": {
      "get": {
        "tags": [
          "me.managedDevice"
        ],
        "summary": "Get managedDevices from me",
        "operationId": "me.GetManagedDevices"
      }
    },
    "/me/managedAppRegistrations": {
      "get": {
        "tags": [
          "me.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from me",
        "operationId": "me.ListManagedAppRegistrations"
      }
    },
    "/me/managedAppRegistrations({managedAppRegistration-id})": {
      "get": {
        "tags": [
          "me.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from me",
        "operationId": "me.GetManagedAppRegistrations"
      }
    },
    "/me/deviceManagementTroubleshootingEvents": {
      "get": {
        "tags": [
          "me.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from me",
        "operationId": "me.ListDeviceManagementTroubleshootingEvents"
      }
    },
    "/me/deviceManagementTroubleshootingEvents({deviceManagementTroubleshootingEvent-id})": {
      "get": {
        "tags": [
          "me.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from me",
        "operationId": "me.GetDeviceManagementTroubleshootingEvents"
      }
    },
    "/me/calendar": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendar from me",
        "operationId": "me.GetCalendar"
      }
    },
    "/me/calendarGroups": {
      "get": {
        "tags": [
          "me.calendarGroup"
        ],
        "summary": "Get calendarGroups from me",
        "operationId": "me.ListCalendarGroups"
      }
    },
    "/me/calendarGroups({calendarGroup-id})": {
      "get": {
        "tags": [
          "me.calendarGroup"
        ],
        "summary": "Get calendarGroups from me",
        "operationId": "me.GetCalendarGroups"
      }
    },
    "/me/calendarView": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get calendarView from me",
        "operationId": "me.ListCalendarView"
      }
    },
    "/me/calendarView({event-id})": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get calendarView from me",
        "operationId": "me.GetCalendarView"
      }
    },
    "/me/calendars": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendars from me",
        "operationId": "me.ListCalendars"
      }
    },
    "/me/calendars({calendar-id})": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendars from me",
        "operationId": "me.GetCalendars"
      }
    },
    "/me/contacts": {
      "get": {
        "tags": [
          "me.contact"
        ],
        "summary": "Get contacts from me",
        "operationId": "me.ListContacts"
      }
    },
    "/me/contacts({contact-id})": {
      "get": {
        "tags": [
          "me.contact"
        ],
        "summary": "Get contacts from me",
        "operationId": "me.GetContacts"
      }
    },
    "/me/contactFolders": {
      "get": {
        "tags": [
          "me.contactFolder"
        ],
        "summary": "Get contactFolders from me",
        "operationId": "me.ListContactFolders"
      }
    },
    "/me/contactFolders({contactFolder-id})": {
      "get": {
        "tags": [
          "me.contactFolder"
        ],
        "summary": "Get contactFolders from me",
        "operationId": "me.GetContactFolders"
      }
    },
    "/me/createdObjects": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get createdObjects from me",
        "operationId": "me.ListCreatedObjects"
      }
    },
    "/me/createdObjects({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get createdObjects from me",
        "operationId": "me.GetCreatedObjects"
      }
    },
    "/me/directReports": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get directReports from me",
        "operationId": "me.ListDirectReports"
      }
    },
    "/me/directReports({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get directReports from me",
        "operationId": "me.GetDirectReports"
      }
    },
    "/me/drive": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drive from me",
        "operationId": "me.GetDrive"
      }
    },
    "/me/drives": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drives from me",
        "operationId": "me.ListDrives"
      }
    },
    "/me/drives({drive-id})": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drives from me",
        "operationId": "me.GetDrives"
      }
    },
    "/me/events": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get events from me",
        "operationId": "me.ListEvents"
      }
    },
    "/me/events({event-id})": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get events from me",
        "operationId": "me.GetEvents"
      }
    },
    "/me/inferenceClassification": {
      "get": {
        "tags": [
          "me.inferenceClassification"
        ],
        "summary": "Get inferenceClassification from me",
        "operationId": "me.GetInferenceClassification"
      }
    },
    "/me/mailFolders": {
      "get": {
        "tags": [
          "me.mailFolder"
        ],
        "summary": "Get mailFolders from me",
        "operationId": "me.ListMailFolders"
      }
    },
    "/me/mailFolders({mailFolder-id})": {
      "get": {
        "tags": [
          "me.mailFolder"
        ],
        "summary": "Get mailFolders from me",
        "operationId": "me.GetMailFolders"
      }
    },
    "/me/manager": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get manager from me",
        "operationId": "me.GetManager"
      }
    },
    "/me/memberOf": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get memberOf from me",
        "operationId": "me.ListMemberOf"
      }
    },
    "/me/memberOf({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get memberOf from me",
        "operationId": "me.GetMemberOf"
      }
    },
    "/me/messages": {
      "get": {
        "tags": [
          "me.message"
        ],
        "summary": "Get messages from me",
        "operationId": "me.ListMessages"
      }
    },
    "/me/messages({message-id})": {
      "get": {
        "tags": [
          "me.message"
        ],
        "summary": "Get messages from me",
        "operationId": "me.GetMessages"
      }
    },
    "/me/outlook": {
      "get": {
        "tags": [
          "me.outlookUser"
        ],
        "summary": "Get outlook from me",
        "operationId": "me.GetOutlook"
      }
    },
    "/me/ownedDevices": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedDevices from me",
        "operationId": "me.ListOwnedDevices"
      }
    },
    "/me/ownedDevices({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedDevices from me",
        "operationId": "me.GetOwnedDevices"
      }
    },
    "/me/ownedObjects": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedObjects from me",
        "operationId": "me.ListOwnedObjects"
      }
    },
    "/me/ownedObjects({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedObjects from me",
        "operationId": "me.GetOwnedObjects"
      }
    },
    "/me/photo": {
      "get": {
        "tags": [
          "me.profilePhoto"
        ],
        "summary": "Get photo from me",
        "operationId": "me.GetPhoto"
      }
    },
    "/me/registeredDevices": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get registeredDevices from me",
        "operationId": "me.ListRegisteredDevices"
      }
    },
    "/me/registeredDevices({directoryObject-id})": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get registeredDevices from me",
        "operationId": "me.GetRegisteredDevices"
      }
    },
    "/me/activities": {
      "get": {
        "tags": [
          "me.userActivity"
        ],
        "summary": "Get activities from me",
        "operationId": "me.ListActivities"
      }
    },
    "/me/activities({userActivity-id})": {
      "get": {
        "tags": [
          "me.userActivity"
        ],
        "summary": "Get activities from me",
        "operationId": "me.GetActivities"
      }
    },
    "/me/extensions": {
      "get": {
        "tags": [
          "me.extension"
        ],
        "summary": "Get extensions from me",
        "operationId": "me.ListExtensions"
      }
    },
    "/me/extensions({extension-id})": {
      "get": {
        "tags": [
          "me.extension"
        ],
        "summary": "Get extensions from me",
        "operationId": "me.GetExtensions"
      }
    },
    "/me/licenseDetails": {
      "get": {
        "tags": [
          "me.licenseDetails"
        ],
        "summary": "Get licenseDetails from me",
        "operationId": "me.ListLicenseDetails"
      }
    },
    "/me/licenseDetails({licenseDetails-id})": {
      "get": {
        "tags": [
          "me.licenseDetails"
        ],
        "summary": "Get licenseDetails from me",
        "operationId": "me.GetLicenseDetails"
      }
    },
    "/me/onenote": {
      "get": {
        "tags": [
          "me.onenote"
        ],
        "summary": "Get onenote from me",
        "operationId": "me.GetOnenote"
      }
    },
    "/me/people": {
      "get": {
        "tags": [
          "me.person"
        ],
        "summary": "Get people from me",
        "operationId": "me.ListPeople"
      }
    },
    "/me/people({person-id})": {
      "get": {
        "tags": [
          "me.person"
        ],
        "summary": "Get people from me",
        "operationId": "me.GetPeople"
      }
    },
    "/me/planner": {
      "get": {
        "tags": [
          "me.plannerUser"
        ],
        "summary": "Get planner from me",
        "operationId": "me.GetPlanner"
      }
    },
    "/organization": {
      "get": {
        "tags": [
          "organization.organization"
        ],
        "summary": "Get organization",
        "operationId": "organization.organization.GetOrganization",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "organization.organization"
        ],
        "summary": "Update organization",
        "operationId": "organization.organization.UpdateOrganization",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/organization/extensions": {
      "get": {
        "tags": [
          "organization.extension"
        ],
        "summary": "Get extensions from organization",
        "operationId": "organization.ListExtensions"
      }
    },
    "/organization/extensions({extension-id})": {
      "get": {
        "tags": [
          "organization.extension"
        ],
        "summary": "Get extensions from organization",
        "operationId": "organization.GetExtensions"
      }
    },
    "/planner": {
      "get": {
        "tags": [
          "planner.planner"
        ],
        "summary": "The **planner** resource is available at the root of the graph.",
        "operationId": "planner.planner.GetPlanner"
      },
      "patch": {
        "tags": [
          "planner.planner"
        ],
        "summary": "Update planner",
        "operationId": "planner.planner.UpdatePlanner"
      }
    },
    "/planner/buckets": {
      "get": {
        "tags": [
          "planner.plannerBucket"
        ],
        "summary": "Get buckets from planner",
        "operationId": "planner.ListBuckets"
      }
    },
    "/planner/buckets({plannerBucket-id})": {
      "get": {
        "tags": [
          "planner.plannerBucket"
        ],
        "summary": "Get buckets from planner",
        "operationId": "planner.GetBuckets"
      }
    },
    "/planner/plans": {
      "get": {
        "tags": [
          "planner.plannerPlan"
        ],
        "summary": "Get plans from planner",
        "operationId": "planner.ListPlans"
      }
    },
    "/planner/plans({plannerPlan-id})": {
      "get": {
        "tags": [
          "planner.plannerPlan"
        ],
        "summary": "Get plans from planner",
        "operationId": "planner.GetPlans"
      }
    },
    "/planner/tasks": {
      "get": {
        "tags": [
          "planner.plannerTask"
        ],
        "summary": "Get tasks from planner",
        "operationId": "planner.ListTasks"
      }
    },
    "/planner/tasks({plannerTask-id})": {
      "get": {
        "tags": [
          "planner.plannerTask"
        ],
        "summary": "Get tasks from planner",
        "operationId": "planner.GetTasks"
      }
    },
    "/reports": {
      "get": {
        "tags": [
          "reports.reportRoot"
        ],
        "summary": "Get reports",
        "operationId": "reports.reportRoot.GetReportRoot"
      },
      "patch": {
        "tags": [
          "reports.reportRoot"
        ],
        "summary": "Update reports",
        "operationId": "reports.reportRoot.UpdateReportRoot"
      }
    },
    "/security": {
      "get": {
        "tags": [
          "security.security"
        ],
        "summary": "The **security** resource is available at the root of the graph.",
        "operationId": "security.security.GetSecurity"
      },
      "patch": {
        "tags": [
          "security.security"
        ],
        "summary": "Update security",
        "operationId": "security.security.UpdateSecurity"
      }
    },
    "/security/alerts": {
      "get": {
        "tags": [
          "security.alert"
        ],
        "summary": "Get alerts from security",
        "operationId": "security.ListAlerts"
      }
    },
    "/security/alerts()": {
      "get": {
        "tags": [
          "security.alert"
        ],
        "summary": "Get alerts from security",
        "operationId": "security.GetAlerts"
      }
    },
    "/groups/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.group.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/microsoft.graph.reminderView(endDateTime={endDateTime},startDateTime={startDateTime})": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function reminderView",
        "operationId": "users.user.reminderView.eea660972a012377469f1711"
      }
    },
    "/me/microsoft.graph.reminderView(endDateTime={endDateTime},startDateTime={startDateTime})": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function reminderView",
        "operationId": "me.user.reminderView.eea660972a012377469f1711"
      }
    },
    "/reports/microsoft.graph.getEmailActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityCounts",
        "operationId": "reports.reportRoot.getEmailActivityCounts.5ff9c3ff1edf7e31002a9ba5"
      }
    },
    "/reports/microsoft.graph.getEmailActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserCounts",
        "operationId": "reports.reportRoot.getEmailActivityUserCounts.0d71442762927e611f745678"
      }
    },
    "/reports/microsoft.graph.getEmailActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserDetail",
        "operationId": "reports.reportRoot.getEmailActivityUserDetail.49d7dec39a67e89e69979278"
      }
    },
    "/reports/microsoft.graph.getEmailActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserDetail",
        "operationId": "reports.reportRoot.getEmailActivityUserDetail.fd73d2a28e6cb07ad3f037c2"
      }
    },
    "/reports/microsoft.graph.getEmailAppUsageAppsUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageAppsUserCounts",
        "operationId": "reports.reportRoot.getEmailAppUsageAppsUserCounts.12b3d5bb1f7ab643ed649ec8"
      }
    },
    "/reports/microsoft.graph.getEmailAppUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserCounts",
        "operationId": "reports.reportRoot.getEmailAppUsageUserCounts.5ccd568244908718f4056c76"
      }
    },
    "/reports/microsoft.graph.getEmailAppUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserDetail",
        "operationId": "reports.reportRoot.getEmailAppUsageUserDetail.c8ff19ea83f55656ec0519ad"
      }
    },
    "/reports/microsoft.graph.getEmailAppUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserDetail",
        "operationId": "reports.reportRoot.getEmailAppUsageUserDetail.971eabe8d8d80ac30d7a13f8"
      }
    },
    "/reports/microsoft.graph.getEmailAppUsageVersionsUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageVersionsUserCounts",
        "operationId": "reports.reportRoot.getEmailAppUsageVersionsUserCounts.477fca84e1a25a2216ad99b4"
      }
    },
    "/reports/microsoft.graph.getMailboxUsageDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageDetail",
        "operationId": "reports.reportRoot.getMailboxUsageDetail.f1007e9438b51215a1685933"
      }
    },
    "/reports/microsoft.graph.getMailboxUsageMailboxCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageMailboxCounts",
        "operationId": "reports.reportRoot.getMailboxUsageMailboxCounts.59e9ffd250a038d8e4a7b378"
      }
    },
    "/reports/microsoft.graph.getMailboxUsageQuotaStatusMailboxCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageQuotaStatusMailboxCounts",
        "operationId": "reports.reportRoot.getMailboxUsageQuotaStatusMailboxCounts.78e058c80c05eb220ac6727b"
      }
    },
    "/reports/microsoft.graph.getMailboxUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageStorage",
        "operationId": "reports.reportRoot.getMailboxUsageStorage.e7208185d7f600c70353fae3"
      }
    },
    "/reports/microsoft.graph.getOffice365ActivationCounts()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationCounts",
        "operationId": "reports.reportRoot.getOffice365ActivationCounts.70c119abc0af47b59bcd7567"
      }
    },
    "/reports/microsoft.graph.getOffice365ActivationsUserCounts()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationsUserCounts",
        "operationId": "reports.reportRoot.getOffice365ActivationsUserCounts.027ddeb4739542e024ac5c69"
      }
    },
    "/reports/microsoft.graph.getOffice365ActivationsUserDetail()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationsUserDetail",
        "operationId": "reports.reportRoot.getOffice365ActivationsUserDetail.13c71eed2c1809c4ef046862"
      }
    },
    "/reports/microsoft.graph.getOffice365ActiveUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserCounts",
        "operationId": "reports.reportRoot.getOffice365ActiveUserCounts.33a5266df147ae12534c7ac0"
      }
    },
    "/reports/microsoft.graph.getOffice365ActiveUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserDetail",
        "operationId": "reports.reportRoot.getOffice365ActiveUserDetail.3c45b672c9211380cbb93aaf"
      }
    },
    "/reports/microsoft.graph.getOffice365ActiveUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserDetail",
        "operationId": "reports.reportRoot.getOffice365ActiveUserDetail.b4ad29d72e04cb5f928d3302"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityCounts",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityCounts.949c7d25b084ce1883183854"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityDetail",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityDetail.314f5e2cd90e9f0e27e87d05"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityDetail",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityDetail.584102add469342246dea4a6"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityFileCounts",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityFileCounts.c7ec8e7db234bd53f643c23e"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityGroupCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityGroupCounts",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityGroupCounts.711b8131adbf47b5b33fbf20"
      }
    },
    "/reports/microsoft.graph.getOffice365GroupsActivityStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityStorage",
        "operationId": "reports.reportRoot.getOffice365GroupsActivityStorage.40c5f2e237d06d8caa408950"
      }
    },
    "/reports/microsoft.graph.getOffice365ServicesUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ServicesUserCounts",
        "operationId": "reports.reportRoot.getOffice365ServicesUserCounts.b83f115e25e31b7769f7053c"
      }
    },
    "/reports/microsoft.graph.getOneDriveActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityFileCounts",
        "operationId": "reports.reportRoot.getOneDriveActivityFileCounts.53a4be96636f99c5f73d6931"
      }
    },
    "/reports/microsoft.graph.getOneDriveActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserCounts",
        "operationId": "reports.reportRoot.getOneDriveActivityUserCounts.79a3a31381ccd6da60da969e"
      }
    },
    "/reports/microsoft.graph.getOneDriveActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserDetail",
        "operationId": "reports.reportRoot.getOneDriveActivityUserDetail.2cbbd80c09870da45712e816"
      }
    },
    "/reports/microsoft.graph.getOneDriveActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserDetail",
        "operationId": "reports.reportRoot.getOneDriveActivityUserDetail.0238a15d6c6ea1fdb9760409"
      }
    },
    "/reports/microsoft.graph.getOneDriveUsageAccountCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountCounts",
        "operationId": "reports.reportRoot.getOneDriveUsageAccountCounts.a3ab3d55a57df63702676685"
      }
    },
    "/reports/microsoft.graph.getOneDriveUsageAccountDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountDetail",
        "operationId": "reports.reportRoot.getOneDriveUsageAccountDetail.68875840255f867581b26939"
      }
    },
    "/reports/microsoft.graph.getOneDriveUsageAccountDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountDetail",
        "operationId": "reports.reportRoot.getOneDriveUsageAccountDetail.021e1e7fd462af6aa0009b62"
      }
    },
    "/reports/microsoft.graph.getOneDriveUsageFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageFileCounts",
        "operationId": "reports.reportRoot.getOneDriveUsageFileCounts.5d09834b79b5acb6177db2a7"
      }
    },
    "/reports/microsoft.graph.getOneDriveUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageStorage",
        "operationId": "reports.reportRoot.getOneDriveUsageStorage.6c49a3945e7d02266faa0d2c"
      }
    },
    "/reports/microsoft.graph.getSharePointActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityFileCounts",
        "operationId": "reports.reportRoot.getSharePointActivityFileCounts.bbf804882b0fbe65048aac08"
      }
    },
    "/reports/microsoft.graph.getSharePointActivityPages(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityPages",
        "operationId": "reports.reportRoot.getSharePointActivityPages.f887ef78417faeeec6dc8e6a"
      }
    },
    "/reports/microsoft.graph.getSharePointActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserCounts",
        "operationId": "reports.reportRoot.getSharePointActivityUserCounts.2adc15c788d3eb009f33f5f7"
      }
    },
    "/reports/microsoft.graph.getSharePointActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserDetail",
        "operationId": "reports.reportRoot.getSharePointActivityUserDetail.e8387fedf2444768ad8b3b97"
      }
    },
    "/reports/microsoft.graph.getSharePointActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserDetail",
        "operationId": "reports.reportRoot.getSharePointActivityUserDetail.482d6fd117a75a1f6fba584e"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsageDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageDetail",
        "operationId": "reports.reportRoot.getSharePointSiteUsageDetail.208fe1ab10faafeb543ab705"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsageDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageDetail",
        "operationId": "reports.reportRoot.getSharePointSiteUsageDetail.06e5704078f61c65140119cb"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsageFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageFileCounts",
        "operationId": "reports.reportRoot.getSharePointSiteUsageFileCounts.155ba9ba076d3f316ad30a0a"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsagePages(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsagePages",
        "operationId": "reports.reportRoot.getSharePointSiteUsagePages.988cbbc218485558a0b934b3"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsageSiteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageSiteCounts",
        "operationId": "reports.reportRoot.getSharePointSiteUsageSiteCounts.c07df42031bee73730772e57"
      }
    },
    "/reports/microsoft.graph.getSharePointSiteUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageStorage",
        "operationId": "reports.reportRoot.getSharePointSiteUsageStorage.9f73ac820d2bf382be19fe49"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessActivityCounts.73b877a5582512351a4b5aff"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessActivityUserCounts.9341cc2b78ef779562e1b522"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserDetail",
        "operationId": "reports.reportRoot.getSkypeForBusinessActivityUserDetail.b224074b80c404bd6f360ae6"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserDetail",
        "operationId": "reports.reportRoot.getSkypeForBusinessActivityUserDetail.23b7c50a041d2e8efb340e29"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageDistributionUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessDeviceUsageDistributionUserCounts.a578976a66bed8f5e995e319"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessDeviceUsageUserCounts.57d56a2163ef120cdc2490b8"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getSkypeForBusinessDeviceUsageUserDetail.c0a05adc8b18000011f482cb"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getSkypeForBusinessDeviceUsageUserDetail.96b5eb20baed695ce1d24c8c"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessOrganizerActivityCounts.e47ebc16d0b08668af9b52ad"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityMinuteCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessOrganizerActivityMinuteCounts.c25e2d8f12de360c913065a5"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessOrganizerActivityUserCounts.f276d6b31ea5f120a74fee07"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessParticipantActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessParticipantActivityCounts.86f01d23d87a3b2dea6a385e"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessParticipantActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityMinuteCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessParticipantActivityMinuteCounts.700bfde176771e61514879f8"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessParticipantActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessParticipantActivityUserCounts.f2f5180b73976b2359805488"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessPeerToPeerActivityCounts.b145849bf239fc4acae0116b"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityMinuteCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessPeerToPeerActivityMinuteCounts.9cab2135d898e5b695855b02"
      }
    },
    "/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityUserCounts",
        "operationId": "reports.reportRoot.getSkypeForBusinessPeerToPeerActivityUserCounts.dff498d2c383219ee7cd2baf"
      }
    },
    "/reports/microsoft.graph.getTeamsDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageDistributionUserCounts",
        "operationId": "reports.reportRoot.getTeamsDeviceUsageDistributionUserCounts.36cde5cbd16df29867e7c4ea"
      }
    },
    "/reports/microsoft.graph.getTeamsDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserCounts",
        "operationId": "reports.reportRoot.getTeamsDeviceUsageUserCounts.680392c31af27c05173b35cb"
      }
    },
    "/reports/microsoft.graph.getTeamsDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getTeamsDeviceUsageUserDetail.7c619f1c0a5bc154156e45a2"
      }
    },
    "/reports/microsoft.graph.getTeamsDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getTeamsDeviceUsageUserDetail.9b87dcb5b7520a515ee6473e"
      }
    },
    "/reports/microsoft.graph.getTeamsUserActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityCounts",
        "operationId": "reports.reportRoot.getTeamsUserActivityCounts.01c2ff207f065545232a4cc2"
      }
    },
    "/reports/microsoft.graph.getTeamsUserActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserCounts",
        "operationId": "reports.reportRoot.getTeamsUserActivityUserCounts.44ad4eca3a9b4a7b3458793f"
      }
    },
    "/reports/microsoft.graph.getTeamsUserActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserDetail",
        "operationId": "reports.reportRoot.getTeamsUserActivityUserDetail.d26389babe7c48a4569d980c"
      }
    },
    "/reports/microsoft.graph.getTeamsUserActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserDetail",
        "operationId": "reports.reportRoot.getTeamsUserActivityUserDetail.a74f1f8d7c706cf67ca19cf1"
      }
    },
    "/reports/microsoft.graph.getYammerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityCounts",
        "operationId": "reports.reportRoot.getYammerActivityCounts.d6da704787ac396a023345cd"
      }
    },
    "/reports/microsoft.graph.getYammerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserCounts",
        "operationId": "reports.reportRoot.getYammerActivityUserCounts.51c76ce0bef4c6547701ac1f"
      }
    },
    "/reports/microsoft.graph.getYammerActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserDetail",
        "operationId": "reports.reportRoot.getYammerActivityUserDetail.09fc912d428fb73b604c6bf7"
      }
    },
    "/reports/microsoft.graph.getYammerActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserDetail",
        "operationId": "reports.reportRoot.getYammerActivityUserDetail.c80d2e9473101ab2eb597bc5"
      }
    },
    "/reports/microsoft.graph.getYammerDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageDistributionUserCounts",
        "operationId": "reports.reportRoot.getYammerDeviceUsageDistributionUserCounts.1fe0d5a9b7ddca849c32753d"
      }
    },
    "/reports/microsoft.graph.getYammerDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserCounts",
        "operationId": "reports.reportRoot.getYammerDeviceUsageUserCounts.06cad47a723e231d41efc932"
      }
    },
    "/reports/microsoft.graph.getYammerDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getYammerDeviceUsageUserDetail.d2c5f42c37f4faab60034e3d"
      }
    },
    "/reports/microsoft.graph.getYammerDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserDetail",
        "operationId": "reports.reportRoot.getYammerDeviceUsageUserDetail.72d057f2a4741325f5a9bdbc"
      }
    },
    "/reports/microsoft.graph.getYammerGroupsActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityCounts",
        "operationId": "reports.reportRoot.getYammerGroupsActivityCounts.02c28af8a9f2b5cd66e41712"
      }
    },
    "/reports/microsoft.graph.getYammerGroupsActivityDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityDetail",
        "operationId": "reports.reportRoot.getYammerGroupsActivityDetail.0ba8882e1710d81f4c46f697"
      }
    },
    "/reports/microsoft.graph.getYammerGroupsActivityDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityDetail",
        "operationId": "reports.reportRoot.getYammerGroupsActivityDetail.9981731ae22e2449a3aaafb7"
      }
    },
    "/reports/microsoft.graph.getYammerGroupsActivityGroupCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityGroupCounts",
        "operationId": "reports.reportRoot.getYammerGroupsActivityGroupCounts.e10c91249509b79e861661dc"
      }
    },
    "/users/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/activities/microsoft.graph.recent()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function recent",
        "operationId": "users.user.recent.d3f031c1d9c48074285bfbc7"
      }
    },
    "/me/activities/microsoft.graph.recent()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function recent",
        "operationId": "me.user.recent.d3f031c1d9c48074285bfbc7"
      }
    },
    "/groups({group-id})/calendarView/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.group.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/groups({group-id})/events/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.group.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/calendarView/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/events/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/calendarView/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/events/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/contactFolders/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/contactFolders/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/drives({drive-id})/microsoft.graph.recent()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function recent",
        "operationId": "drives.drive.recent.d3f031c1d9c48074285bfbc7"
      }
    },
    "/drives({drive-id})/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.drive.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/drives({drive-id})/microsoft.graph.sharedWithMe()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function sharedWithMe",
        "operationId": "drives.drive.sharedWithMe.2f10bc98d2c4ee31f6daa2c7"
      }
    },
    "/users({user-id})/mailFolders/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/mailFolders/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/outlook/microsoft.graph.supportedLanguages()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function supportedLanguages",
        "operationId": "users.user.supportedLanguages.e62818f06a0eb7aaadd93841"
      }
    },
    "/me/outlook/microsoft.graph.supportedLanguages()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function supportedLanguages",
        "operationId": "me.user.supportedLanguages.e62818f06a0eb7aaadd93841"
      }
    },
    "/users({user-id})/outlook/microsoft.graph.supportedTimeZones()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "users.user.supportedTimeZones.7bc4e7721f5ce3d55d14520b"
      }
    },
    "/me/outlook/microsoft.graph.supportedTimeZones()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "me.user.supportedTimeZones.7bc4e7721f5ce3d55d14520b"
      }
    },
    "/users({user-id})/outlook/microsoft.graph.supportedTimeZones(TimeZoneStandard={TimeZoneStandard})": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "users.user.supportedTimeZones.5fe7be2bce7f192b65a38aa7"
      }
    },
    "/me/outlook/microsoft.graph.supportedTimeZones(TimeZoneStandard={TimeZoneStandard})": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "me.user.supportedTimeZones.5fe7be2bce7f192b65a38aa7"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.722655a427602f57c8636c75"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.722655a427602f57c8636c75"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "drives.drive.delta.722655a427602f57c8636c75"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.722655a427602f57c8636c75"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.722655a427602f57c8636c75"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "shares.sharedDriveItem.delta.722655a427602f57c8636c75"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.drive.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.drive.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.drive.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.sharedDriveItem.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.sharedDriveItem.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.sharedDriveItem.search.15e9ccdaa36cf21169027b47"
      }
    },
    "/users({user-id})/contacts/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/contacts/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/users({user-id})/messages/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "users.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "users.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/me/messages/microsoft.graph.delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.user.delta.8fda216f08e1eb50d1a3787b"
      }
    },
    "/directoryObjects/microsoft.graph.getByIds": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getByIds",
        "operationId": "directoryObjects.directoryObject.getByIds"
      }
    },
    "/users({user-id})/microsoft.graph.assignLicense": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action assignLicense",
        "operationId": "users.user.assignLicense"
      }
    },
    "/me/microsoft.graph.assignLicense": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action assignLicense",
        "operationId": "me.user.assignLicense"
      }
    },
    "/users({user-id})/microsoft.graph.findMeetingTimes": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action findMeetingTimes",
        "operationId": "users.user.findMeetingTimes"
      }
    },
    "/me/microsoft.graph.findMeetingTimes": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action findMeetingTimes",
        "operationId": "me.user.findMeetingTimes"
      }
    },
    "/users({user-id})/microsoft.graph.getMailTips": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action getMailTips",
        "operationId": "users.user.getMailTips"
      }
    },
    "/me/microsoft.graph.getMailTips": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action getMailTips",
        "operationId": "me.user.getMailTips"
      }
    },
    "/users({user-id})/microsoft.graph.sendMail": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action sendMail",
        "operationId": "users.user.sendMail"
      }
    },
    "/me/microsoft.graph.sendMail": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action sendMail",
        "operationId": "me.user.sendMail"
      }
    },
    "/directoryObjects({directoryObject-id})/microsoft.graph.checkMemberGroups": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action checkMemberGroups",
        "operationId": "directoryObjects.directoryObject.checkMemberGroups"
      }
    },
    "/directoryObjects({directoryObject-id})/microsoft.graph.getMemberGroups": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getMemberGroups",
        "operationId": "directoryObjects.directoryObject.getMemberGroups"
      }
    },
    "/directoryObjects({directoryObject-id})/microsoft.graph.getMemberObjects": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getMemberObjects",
        "operationId": "directoryObjects.directoryObject.getMemberObjects"
      }
    },
    "/domains({domain-id})/microsoft.graph.verify": {
      "post": {
        "tags": [
          "domains.Actions"
        ],
        "summary": "Invoke action verify",
        "operationId": "domains.domain.verify"
      }
    },
    "/groups({group-id})/microsoft.graph.addFavorite": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action addFavorite",
        "operationId": "groups.group.addFavorite"
      }
    },
    "/groups({group-id})/microsoft.graph.removeFavorite": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action removeFavorite",
        "operationId": "groups.group.removeFavorite"
      }
    },
    "/groups({group-id})/microsoft.graph.renew": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action renew",
        "operationId": "groups.group.renew"
      }
    },
    "/groups({group-id})/microsoft.graph.resetUnseenCount": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action resetUnseenCount",
        "operationId": "groups.group.resetUnseenCount"
      }
    },
    "/groups({group-id})/microsoft.graph.subscribeByMail": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action subscribeByMail",
        "operationId": "groups.group.subscribeByMail"
      }
    },
    "/groups({group-id})/microsoft.graph.unsubscribeByMail": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action unsubscribeByMail",
        "operationId": "groups.group.unsubscribeByMail"
      }
    },
    "/directoryObjects({directoryObject-id})/microsoft.graph.restore": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action restore",
        "operationId": "directoryObjects.directoryObject.restore"
      }
    },
    "/groups({group-id})/calendarView({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "groups.group.accept"
      }
    },
    "/groups({group-id})/events({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "groups.group.accept"
      }
    },
    "/users({user-id})/calendarView({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "users.user.accept"
      }
    },
    "/users({user-id})/events({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "users.user.accept"
      }
    },
    "/me/calendarView({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "me.user.accept"
      }
    },
    "/me/events({event-id})/microsoft.graph.accept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action accept",
        "operationId": "me.user.accept"
      }
    },
    "/groups({group-id})/calendarView({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "groups.group.decline"
      }
    },
    "/groups({group-id})/events({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "groups.group.decline"
      }
    },
    "/users({user-id})/calendarView({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "users.user.decline"
      }
    },
    "/users({user-id})/events({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "users.user.decline"
      }
    },
    "/me/calendarView({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "me.user.decline"
      }
    },
    "/me/events({event-id})/microsoft.graph.decline": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action decline",
        "operationId": "me.user.decline"
      }
    },
    "/groups({group-id})/calendarView({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "groups.group.dismissReminder"
      }
    },
    "/groups({group-id})/events({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "groups.group.dismissReminder"
      }
    },
    "/users({user-id})/calendarView({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "users.user.dismissReminder"
      }
    },
    "/users({user-id})/events({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "users.user.dismissReminder"
      }
    },
    "/me/calendarView({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "me.user.dismissReminder"
      }
    },
    "/me/events({event-id})/microsoft.graph.dismissReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action dismissReminder",
        "operationId": "me.user.dismissReminder"
      }
    },
    "/groups({group-id})/calendarView({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "groups.group.snoozeReminder"
      }
    },
    "/groups({group-id})/events({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "groups.group.snoozeReminder"
      }
    },
    "/users({user-id})/calendarView({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "users.user.snoozeReminder"
      }
    },
    "/users({user-id})/events({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "users.user.snoozeReminder"
      }
    },
    "/me/calendarView({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "me.user.snoozeReminder"
      }
    },
    "/me/events({event-id})/microsoft.graph.snoozeReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action snoozeReminder",
        "operationId": "me.user.snoozeReminder"
      }
    },
    "/groups({group-id})/calendarView({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "groups.group.tentativelyAccept"
      }
    },
    "/groups({group-id})/events({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "groups.group.tentativelyAccept"
      }
    },
    "/users({user-id})/calendarView({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "users.user.tentativelyAccept"
      }
    },
    "/users({user-id})/events({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "users.user.tentativelyAccept"
      }
    },
    "/me/calendarView({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "me.user.tentativelyAccept"
      }
    },
    "/me/events({event-id})/microsoft.graph.tentativelyAccept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action tentativelyAccept",
        "operationId": "me.user.tentativelyAccept"
      }
    },
    "/users({user-id})/mailFolders({mailFolder-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "users.user.copy"
      }
    },
    "/me/mailFolders({mailFolder-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "me.user.copy"
      }
    },
    "/users({user-id})/mailFolders({mailFolder-id})/microsoft.graph.move": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action move",
        "operationId": "users.user.move"
      }
    },
    "/me/mailFolders({mailFolder-id})/microsoft.graph.move": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action move",
        "operationId": "me.user.move"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "users.user.copy"
      }
    },
    "/me/messages({message-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "me.user.copy"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.createForward": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action createForward",
        "operationId": "users.user.createForward"
      }
    },
    "/me/messages({message-id})/microsoft.graph.createForward": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action createForward",
        "operationId": "me.user.createForward"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.createReply": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action createReply",
        "operationId": "users.user.createReply"
      }
    },
    "/me/messages({message-id})/microsoft.graph.createReply": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action createReply",
        "operationId": "me.user.createReply"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.createReplyAll": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action createReplyAll",
        "operationId": "users.user.createReplyAll"
      }
    },
    "/me/messages({message-id})/microsoft.graph.createReplyAll": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action createReplyAll",
        "operationId": "me.user.createReplyAll"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.forward": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action forward",
        "operationId": "users.user.forward"
      }
    },
    "/me/messages({message-id})/microsoft.graph.forward": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action forward",
        "operationId": "me.user.forward"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.move": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action move",
        "operationId": "users.user.move"
      }
    },
    "/me/messages({message-id})/microsoft.graph.move": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action move",
        "operationId": "me.user.move"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.reply": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action reply",
        "operationId": "users.user.reply"
      }
    },
    "/me/messages({message-id})/microsoft.graph.reply": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action reply",
        "operationId": "me.user.reply"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.replyAll": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action replyAll",
        "operationId": "users.user.replyAll"
      }
    },
    "/me/messages({message-id})/microsoft.graph.replyAll": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action replyAll",
        "operationId": "me.user.replyAll"
      }
    },
    "/users({user-id})/messages({message-id})/microsoft.graph.send": {
      "post": {
        "tags": [
          "users.Actions"
        ],
        "summary": "Invoke action send",
        "operationId": "users.user.send"
      }
    },
    "/me/messages({message-id})/microsoft.graph.send": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action send",
        "operationId": "me.user.send"
      }
    },
    "/groups({group-id})/threads({conversationThread-id})/microsoft.graph.reply": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action reply",
        "operationId": "groups.group.reply"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "drives.drive.copy"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "drives.drive.copy"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "drives.drive.copy"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "shares.sharedDriveItem.copy"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "shares.sharedDriveItem.copy"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action copy",
        "operationId": "shares.sharedDriveItem.copy"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "drives.drive.createLink"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "drives.drive.createLink"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "drives.drive.createLink"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "shares.sharedDriveItem.createLink"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "shares.sharedDriveItem.createLink"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createLink",
        "operationId": "shares.sharedDriveItem.createLink"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "drives.drive.invite"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "drives.drive.invite"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "drives.drive.invite"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "shares.sharedDriveItem.invite"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "shares.sharedDriveItem.invite"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action invite",
        "operationId": "shares.sharedDriveItem.invite"
      }
    },
    "/drives({drive-id})/items({driveItem-id})/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.drive.createUploadSession"
      }
    },
    "/drives({drive-id})/root/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.drive.createUploadSession"
      }
    },
    "/drives({drive-id})/special({driveItem-id})/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.drive.createUploadSession"
      }
    },
    "/shares({sharedDriveItem-id})/driveItem/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.sharedDriveItem.createUploadSession"
      }
    },
    "/shares({sharedDriveItem-id})/items({driveItem-id})/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.sharedDriveItem.createUploadSession"
      }
    },
    "/shares({sharedDriveItem-id})/root/microsoft.graph.createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.sharedDriveItem.createUploadSession"
      }
    }
  },
  "securityDefinitions": {
    "Delegated (work or school account)": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://graph.microsoft.com/",
      "scopes": {
        "Bookings.Read.All": " Allows an app to read Bookings appointments, businesses, customers, services, and staff on behalf of the signed-in user. Intended for read-only applications. Typical target user is the customer of a booking business. ",
        "Bookings.ReadWrite.Appointments": "Allows an app to read and write Bookings appointments and customers, and additionally allows reading businesses, services, and staff on behalf of the signed-in user. Intended for scheduling applications which need to manipulate appointments and customers. Cannot change fundamental information about the booking business, nor its services and staff members. Typical target user is the customer of a booking business.",
        "Bookings.ReadWrite.All": "Allows an app to read and write Bookings appointments, businesses, customers, services, and staff on behalf of the signed-in user. Does not allow create, delete, or publish of Bookings businesses. Intended for management applications that manipulate existing businesses, their services and staff members. Cannot create, delete, or change the publishing status of a booking business. Typical target user is the support staff of an organization.",
        "Bookings.Manage": "Allows an app to read, write, and manage Bookings appointments, businesses, customers, services, and staff on behalf of the signed-in user. . Allows the app to have full access. Intended for a full management experience. Typical target user is the administrator of an organization.",
        "Calendars.Read": "    Read user calendars .Allows the app to read events in user calendars. ",
        "Calendars.Read.Shared": "    Read user and shared calendars .Allows the app to read events in all calendars that the user can access, including delegate and shared calendars. ",
        "Calendars.ReadWrite": "    Have full access to user calendars .Allows the app to create, read, update, and delete events in user calendars. ",
        "Calendars.ReadWrite.Shared": "    Read and write user and shared calendars .Allows the app to create, read, update and delete events in all calendars the user has permissions to access. This includes delegate and shared calendars.",
        "Contacts.Read": "Read user contacts  .Allows the app to read user contacts. ",
        "Contacts.Read.Shared": "    Read user and shared contacts .Allows the app to read contacts that the user has permissions to access, including the user's own and shared contacts. ",
        "Contacts.ReadWrite": "    Have full access to user contacts .Allows the app to create, read, update, and delete user contacts. ",
        "Contacts.ReadWrite.Shared": "    Read and write user and shared contacts .Allows the app to create, read, update and delete contacts that the user has permissions to, including the user's own and shared contacts. ",
        "Device.Read": "    Read user devices .Allows the app to read a user's list of devices on behalf of the signed-in user. ",
        "Device.Command": "    Communicate with user devices .Allows the app to launch another app or communicate with another app on a user's device on behalf of the signed-in user. ",
        "Directory.Read.All": "    Read directory data. Allows the app to read data in your organization's directory, such as users, groups and apps.",
        "Directory.ReadWrite.All": "    Read and write directory data. Allows the app to read and write data in your organization's directory, such as users, and groups. It does not allow the app to delete users or groups, or reset user passwords. ",
        "Directory.AccessAsUser.All": "    Access directory as the signed-in user. Allows the app to have the same access to information in the directory as the signed-in user. ",
        "EduAdministration.Read": "    Read education app settings. Allows the app to read education app settings on behalf of the user. ",
        "EduAdministration.ReadWrite": "    Manage education app settings. Allows the app to manage education app settings on behalf of the user. ",
        "EduAssignments.ReadBasic": "    Read users' class assignments without grades. Allows the app to read assignments without grades on behalf of the user ",
        "EduAssignments.ReadWriteBasic": "    Read and write users' class assignments without grades. Allows the app to read and write assignments without grades on behalf of the user ",
        "EduAssignments.Read": "    Read users' view of class assignments and their grades. Allows the app to read assignments and their grades on behalf of the user",
        "EduAssignments.ReadWrite": "    Read and write users' view of class assignments and their grades. Allows the app to read and write assignments and their grades on behalf of the user",
        "EduRostering.ReadBasic": "    Read a limited subset of users' view of the roster. Allows the app to read a limited subset of the data from the  structure of schools and classes in an organization's roster and  education-specific information about users to be read on behalf of the user. ",
        "Files.Read": "Read user files. Allows the app to read the signed-in user's files. ",
        "Files.Read.All": "Read all files that user can access. Allows the app to read all files the signed-in user can access. ",
        "Files.ReadWrite": "Have full access to user files. Allows the app to read, create, update, and delete the signed-in user's files. ",
        "Files.ReadWrite.All": "Have full access to all files user can access. Allows the app to read, create, update, and delete all files the signed-in user can access. ",
        "Files.ReadWrite.AppFolder": "Have full access to the application's folder (preview). (Preview) Allows the app to read, create, update, and delete files in the application's folder. ",
        "Files.Read.Selected": "Read files that the user selects. **Limited support in Microsoft Graph; see Remarks** . (Preview) Allows the app to read files that the user selects. The app has access for several hours after the user selects a file. ",
        "Files.ReadWrite.Selected": "Read and write files that the user selects. **Limited support in Microsoft Graph; see Remarks** . (Preview) Allows the app to read and write files that the user selects. The app has access for several hours after the user selects a file. ",
        "Group.Read.All": "Read all groups. Allows the app to list groups, and to read their properties and all group memberships on behalf of the signed-in user. Also allows the app to read calendar, conversations, files, and other group content for all groups the signed-in user can access. ",
        "Group.ReadWrite.All": "Read and write all groups. Allows the app to create groups and read all group properties and memberships on behalf of the signed-in user. Additionally allows group owners to manage their groups and allows group members to update group content. ",
        "IdentityRiskEvent.Read.All": "  Read identity risk event information. Allows the app to read identity risk event information for all users in your organization on behalf of the signed-in user. ",
        "IdentityProvider.Read.All": "  Read identity provider information. Allows the app to read identity providers configured in your Azure AD or Azure AD B2C tenant on behalf of the signed-in user. ",
        "IdentityProvider.ReadWrite.All": "  Read and write identity provider information. Allows the app to read or write identity providers configured in your Azure AD or Azure AD B2C tenant on behalf of the signed-in user. ",
        "DeviceManagementApps.Read.All": "Read Microsoft Intune apps. Allows the app to read the properties, group assignments and status of apps, app configurations and app protection policies managed by Microsoft Intune. ",
        "DeviceManagementApps.ReadWrite.All": "Read and write Microsoft Intune apps. Allows the app to read and write the properties, group assignments and status of apps, app configurations and app protection policies managed by Microsoft Intune. ",
        "DeviceManagementConfiguration.Read.All": "Read Microsoft Intune device configuration and policies. Allows the app to read properties of Microsoft Intune-managed device configuration and device compliance policies and their assignment to groups. ",
        "DeviceManagementConfiguration.ReadWrite.All": "Read and write Microsoft Intune device configuration and policies. Allows the app to read and write properties of Microsoft Intune-managed device configuration and device compliance policies and their assignment to groups. ",
        "DeviceManagementManagedDevices.PrivilegedOperations.All": "Perform user-impacting remote actions on Microsoft Intune devices. Allows the app to perform remote high impact actions such as wiping the device or resetting the passcode on devices managed by Microsoft Intune. ",
        "DeviceManagementManagedDevices.Read.All": "Read Microsoft Intune devices. Allows the app to read the properties of devices managed by Microsoft Intune. ",
        "DeviceManagementManagedDevices.ReadWrite.All": "Read and write Microsoft Intune devices. Allows the app to read and write the properties of devices managed by Microsoft Intune. Does not allow high impact operations such as remote wipe and password reset on the device’s owner. ",
        "DeviceManagementRBAC.Read.All": "Read Microsoft Intune RBAC settings. Allows the app to read the properties relating to the Microsoft Intune Role-Based Access Control (RBAC) settings. ",
        "DeviceManagementRBAC.ReadWrite.All": "Read and write Microsoft Intune RBAC settings. Allows the app to read and write the properties relating to the Microsoft Intune Role-Based Access Control (RBAC) settings. ",
        "DeviceManagementServiceConfig.Read.All": "Read Microsoft Intune configuration. Allows the app to read Intune service properties including device enrollment and third party service connection configuration. ",
        "DeviceManagementServiceConfig.ReadWrite.All": "Read and write Microsoft Intune configuration. Allows the app to read and write Microsoft Intune service properties including device enrollment and third party service connection configuration. ",
        "Mail.Read": "Read user mail. Allows the app to read email in user mailboxes. ",
        "Mail.ReadWrite": "Read and write access to user mail. Allows the app to create, read, update, and delete email in user mailboxes. Does not include permission to send mail.",
        "Mail.Read.Shared": "Read user and shared mail. Allows the app to read mail that the user can access, including the user's own and shared mail. ",
        "Mail.ReadWrite.Shared": "Read and write user and shared mail. Allows the app to create, read, update, and delete mail that the user has permission to access, including the user's own and shared mail. Does not include permission to send mail. ",
        "Mail.Send": "Send mail as a user. Allows the app to send mail as users in the organization. ",
        "Mail.Send.Shared": "Send mail on behalf of others. Allows the app to send mail as the signed-in user, including sending on-behalf of others. ",
        "MailboxSettings.Read": " Read user mailbox settings. Allows the app to the read user's mailbox settings. Does not include permission to send mail. ",
        "MailboxSettings.ReadWrite": " Read and write user mailbox settings. Allows the app to create, read, update, and delete user's mailbox settings. Does not include permission to directly send mail, but allows the app to create rules that can forward or redirect messages. ",
        "Member.Read.Hidden": "Read hidden memberships. Allows the app to read the memberships of hidden groups and administrative units on behalf of the signed-in user, for those hidden groups and administrative units that the signed-in user has access to. ",
        "Notes.Read": "Read user OneNote notebooks. Allows the app to read the titles of OneNote notebooks and sections and to create new pages, notebooks, and sections on behalf of the signed-in user. ",
        "Notes.Create": "Create user OneNote notebooks. Allows the app to read the titles of OneNote notebooks and sections and to create new pages, notebooks, and sections on behalf of the signed-in user.",
        "Notes.ReadWrite": "Read and write user OneNote notebooks. Allows the app to read, share, and modify OneNote notebooks on behalf of the signed-in user. ",
        "Notes.Read.All": "Read all OneNote notebooks that user can access. Allows the app to read OneNote notebooks that the signed-in user has access to in the organization. ",
        "Notes.ReadWrite.All": "Read and write all OneNote notebooks that user can access. Allows the app to read, share, and modify OneNote notebooks that the signed-in user has access to in the organization.",
        "Notes.ReadWrite.CreatedByApp": "Limited notebook access (deprecated). **Deprecated** .Do not use. No privileges are granted by this permission. ",
        "email": "View users' email address. Allows the app to read your users' primary email address. ",
        "offline_access": "Access user's data anytime. Allows the app to read and update user data, even when they are not currently using the app.",
        "openid": "Sign users in. Allows users to sign in to the app with their work or school accounts and allows the app to see basic user profile information.",
        "profile": "View users' basic profile. Allows the app to see your users' basic profile (name, picture, user name).",
        "People.Read": "Read users' relevant people lists. Allows the app to read a scored list of people relevant to the signed-in user. The list can include local contacts, contacts from social networking or your organization's directory, and people from recent communications (such as email and Skype). ",
        "People.Read.All": "Read all users' relevant people lists. Allows the app to read a scored list of people relevant to the signed-in user or other users in the signed-in user's organization. The list can include local contacts, contacts from social networking or your organization's directory, and people from recent communications (such as email and Skype). Also allows the app to search the entire directory of the signed-in user's organization. ",
        "Reports.Read.All": "Read all usage reports. Allows an app to read all service usage reports without a signed-in user. Services that provide usage reports include Office 365 and Azure Active Directory. ",
        "SecurityEvents.Read.All": " Read your organization’s security events. Allows the app to read your organization’s security events on behalf of the signed-in user. ",
        "SecurityEvents.ReadWrite.All": "Read and update your organization’s security events. Allows the app to read your organization’s security events on behalf of the signed-in user. Also allows the app to update editable properties in security events on behalf of the signed-in user. ",
        "Sites.Read.All": "Read items in all site collections. Allows the app to read documents and list items in all site collections on behalf of the signed-in user. ",
        "Sites.ReadWrite.All": "Read and write items in all site collections. Allows the app to edit or delete documents and list items in all site collections on behalf of the signed-in user. ",
        "Sites.Manage.All": "Create, edit, and delete items and lists in all site collections. Allows the app to manage and create lists, documents, and list items in all site collections on behalf of the signed-in user. ",
        "Sites.FullControl.All": "Have full control of all site collections. Allows the app to have full control to SharePoint sites in all site collections on behalf of the signed-in user. ",
        "Tasks.Read": "Read user tasks. Allows the app to read user tasks. ",
        "Tasks.Read.Shared": "Read user and shared tasks. Allows the app to read tasks a user has permissions to access, including their own and shared tasks. ",
        "Tasks.ReadWrite": "Create, read, update and delete user tasks and containers. Allows the app to create, read, update and delete tasks and containers (and tasks in them) that are assigned to or shared with the signed-in user.",
        "Tasks.ReadWrite.Shared": "Read and write user and shared tasks. Allows the app to create, read, update, and delete tasks a user has permissions to, including their own and shared tasks. ",
        "Agreement.Read.All": "Read all terms of use agreements. Allows the app to read terms of use agreements on behalf of the signed-in user. ",
        "Agreement.ReadWrite.All": "Read and write all terms of use agreements. Allows the app to read and write terms of use agreements on behalf of the signed-in user. ",
        "AgreementAcceptance.Read": "Read user terms of use acceptance statuses. Allows the app to read terms of use acceptance statuses on behalf of the signed-in user. ",
        "AgreementAcceptance.Read.All": "Read terms of use acceptance statuses that user can access. Allows the app to read terms of use acceptance statuses on behalf of the signed-in user. ",
        "User.Read": "Sign-in and read user profile. Allows users to sign-in to the app, and allows the app to read the profile of signed-in users. It also allows the app to read basic company information of signed-in users.",
        "User.ReadWrite": "Read and write access to user profile. Allows the app to read the signed-in user's full profile. It also allows the app to update the signed-in user's profile information on their behalf. ",
        "User.ReadBasic.All": "Read all users' basic profiles. Allows the app to read a basic set of profile properties of other users in your organization on behalf of the signed-in user. This includes display name, first and last name, email address, open extensions and photo. Also allows the app to read the full profile of the signed-in user. ",
        "User.Read.All": " Read all users' full profiles. Allows the app to read the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user. ",
        "User.ReadWrite.All": " Read and write all users' full profiles. Allows the app to read and write the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user. Also allows the app to create and delete users as well as reset user passwords on behalf of the signed-in user. ",
        "User.Invite.All": " Invite guest users to the organization. Allows the app to invite guest users to your organization, on behalf of the signed-in user. ",
        "User.Export.All": "Export users' data. Allows the app to export an organizational user's data, when performed by a Company Administrator.",
        "UserActivity.ReadWrite.CreatedByApp": "    Read and write app activity to users' activity feed .Allows the app to read and report the signed-in user's activity in the app. "
      }
    },
    "DelegatedPersonal": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://graph.microsoft.com/",
      "scopes": {
        "Calendars.Read": "    Read user calendars .Allows the app to read events in user calendars. ",
        "Calendars.ReadWrite": "    Have full access to user calendars .Allows the app to create, read, update, and delete events in user calendars. ",
        "Contacts.Read": "    Read user contacts  .Allows the app to read user contacts. ",
        "Contacts.ReadWrite": "    Have full access to user contacts .Allows the app to create, read, update, and delete user contacts. ",
        "Device.Read": "    Read user devices .Allows the app to read a user's list of devices on behalf of the signed-in user. ",
        "Device.Command": "    Communicate with user devices .Allows the app to launch another app or communicate with another app on a user's device on behalf of the signed-in user. ",
        "Files.Read": "Read user files. Allows the app to read the signed-in user's files. ",
        "Files.Read.All": "Read all files that user can access. Allows the app to read all files the signed-in user can access. ",
        "Files.ReadWrite": "Have full access to user files. Allows the app to read, create, update, and delete the signed-in user's files. ",
        "Files.ReadWrite.All": "Have full access to all files user can access. Allows the app to read, create, update, and delete all files the signed-in user can access. ",
        "Mail.ReadWrite": "Read and write access to user mail. Allows the app to create, read, update, and delete email in user mailboxes. Does not include permission to send mail.",
        "Member.Read.Hidden": "Read all hidden memberships. Allows the app to read the memberships of hidden groups and administrative units without a signed-in user. ",
        "Notes.Read": "Read user OneNote notebooks. Allows the app to read the titles of OneNote notebooks and sections and to create new pages, notebooks, and sections on behalf of the signed-in user. ",
        "Notes.Create": "Create user OneNote notebooks. Allows the app to read the titles of OneNote notebooks and sections and to create new pages, notebooks, and sections on behalf of the signed-in user.",
        "Notes.ReadWrite": "Read and write user OneNote notebooks. Allows the app to read, share, and modify OneNote notebooks on behalf of the signed-in user. ",
        "Notes.Read.All": "Read all OneNote notebooks that user can access. Allows the app to read OneNote notebooks that the signed-in user has access to in the organization. ",
        "Tasks.Read": "Read user tasks. Allows the app to read user tasks. ",
        "Tasks.ReadWrite": "Create, read, update and delete user tasks and containers. Allows the app to create, read, update and delete tasks and containers (and tasks in them) that are assigned to or shared with the signed-in user.",
        "User.Read": "Sign-in and read user profile. Allows users to sign-in to the app, and allows the app to read the profile of signed-in users. It also allows the app to read basic company information of signed-in users.",
        "User.ReadWrite": "Read and write access to user profile. Allows the app to read the signed-in user's full profile. It also allows the app to update the signed-in user's profile information on their behalf. ",
        "User.ReadBasic.All": "Read all users' basic profiles. Allows the app to read a basic set of profile properties of other users in your organization on behalf of the signed-in user. This includes display name, first and last name, email address, open extensions and photo. Also allows the app to read the full profile of the signed-in user. ",
        "User.Read.All": " Read all users' full profiles. Allows the app to read the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user. ",
        "User.ReadWrite.All": " Read and write all users' full profiles. Allows the app to read and write the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user. Also allows the app to create and delete users as well as reset user passwords on behalf of the signed-in user. ",
        "User.Invite.All": " Invite guest users to the organization. Allows the app to invite guest users to your organization, on behalf of the signed-in user. ",
        "User.Export.All": "Export users' data. Allows the app to export an organizational user's data, when performed by a Company Administrator.",
        "UserActivity.ReadWrite.CreatedByApp": "    Read and write app activity to users' activity feed .Allows the app to read and report the signed-in user's activity in the app. "
      }
    },
    "Application": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://graph.microsoft.com/",
      "scopes": {
        "Application.ReadWrite.All": "Read and write all apps. Allows the calling app to create, and manage (read, update, update application secrets and delete) applications and service principals without a signed-in user. Does not allow management of consent grants or application assignments to users or groups. ",
        "Application.ReadWrite.OwnedBy": "Manage apps that this app creates or owns. Allows the calling app to create other applications and service principals, and fully manage those applications and service principals (read, update, update application secrets and delete), without a signed-in user. It cannot update any applications that it is not an owner of. Does not allow management of consent grants or application assignments to users or groups. ",
        "Calendars.Read": "    Read calendars in all mailboxes .Allows the app to read events of all calendars without a signed-in user. ",
        "Calendars.ReadWrite": "    Read and write calendars in all mailboxes .Allows the app to create, read, update, and delete events of all calendars without a signed-in user. ",
        "Contacts.Read": "    Read contacts in all mailboxes .Allows the app to read all contacts in all mailboxes without a signed-in user. ",
        "Contacts.ReadWrite": "    Read and write contacts in all mailboxes .Allows the app to create, read, update, and delete all contacts in all mailboxes without a signed-in user. ",
        "Device.ReadWrite.All": "    Read and write devices .Allows the app to read and write all device properties without a signed in user. Does not allow device creation, device deletion, or update of device alternative security identifiers. ",
        "Directory.Read.All": "Read directory data. Allows the app to read data in your organization's directory, such as users, groups and apps, without a signed-in user. ",
        "Directory.ReadWrite.All": "Read and write directory data. Allows the app to read and write data in your organization's directory, such as users, and groups, without a signed-in user. Does not allow user or group deletion. ",
        "EduAssignments.ReadBasic.All": "Read class assignments without grades.Allows the app to read assignments without grades for all users",
        "EduAssignments.ReadWriteBasic.All": "Read and write class assignments without grades. Allows the app to read and write assignments without grades for all users",
        "EduAssignments.Read.All": "Read class assignments with grades. Allows the app to read assignments and their grades for all users ",
        "EduAssignments.ReadWrite.All": "Read and write class assignments with grades. Allows the app to read and write assignments and their grades for all users ",
        "EduRostering.ReadBasic.All": "Read a limited subset of the organization's roster. Allows the app to read a limited subset of both the structure of schools and classes in an organization's roster and education-specific information about all users. ",
        "EduRostering.Read.All": "Read the organization's roster. Allows the app to read the structure of schools and classes in the organization's roster and education-specific information about all users to be read. ",
        "EduRostering.ReadWrite.All": "Read and write the organization's roster. Allows the app to read and write the structure of schools and classes in the organization's roster and education-specific information about all users to be read and written. ",
        "Files.Read.All": "Read files in all site collections. Allows the app to read all files in all site collections without a signed in user. ",
        "Files.ReadWrite.All": "Read and write files in all site collections. Allows the app to read, create, update, and delete all files in all site collections without a signed in user. ",
        "Group.Read.All": "Read all groups. Allows the app to read memberships for all groups without a signed-in user. > **NOTE:** that not all group API supports access using app-only permissions. See [known issues](../concepts/known_issues.md) for examples. ",
        "Group.ReadWrite.All": "Read and write all groups. Allows the app to create groups, read and update group memberships, and delete groups. All of these operations can be performed by the app without a signed-in user. ",
        "IdentityRiskEvent.Read.All": "  Read identity risk event information. Allows the app to read identity risk event information for all users in your organization without a signed-in user. ",
        "Mail.Read": "Read mail in all mailboxes. Allows the app to read mail in all mailboxes without a signed-in user.",
        "Mail.ReadWrite": "Read and write mail in all mailboxes. Allows the app to create, read, update, and delete mail in all mailboxes without a signed-in user. Does not include permission to send mail. ",
        "Mail.Send": "Send mail as any user. Allows the app to send mail as any user without a signed-in user. ",
        "MailboxSettings.Read": " Read all user mailbox settings. Allows the app to read user's mailbox settings without a signed-in user. Does not include permission to send mail. ",
        "MailboxSettings.ReadWrite": "Read and write all user mailbox settings. Allows the app to create, read, update, and delete user's mailbox settings without a signed-in user. Does not include permission to send mail. ",
        "Notes.Read.All": "Read all OneNote notebooks. Allows the app to read all the OneNote notebooks in your organization, without a signed-in user. ",
        "Notes.ReadWrite.All": "Read and write all OneNote notebooks. Allows the app to read, share, and modify all the OneNote notebooks in your organization, without a signed-in user.",
        "People.Read.All": "Read all users' relevant people lists. Allows the app to read a scored list of people relevant to the signed-in user or other users in the signed-in user's organization. .The list can include local contacts, contacts from social networking or your organization's directory, and people from recent communications (such as email and Skype). Also allows the app to search the entire directory of the signed-in user's organization. ",
        "Reports.Read.All": "Read all usage reports. Allows an app to read all service usage reports without a signed-in user. Services that provide usage reports include Office 365 and Azure Active Directory. ",
        "SecurityEvents.Read.All": " Read your organization’s security events. Allows the app to read your organization’s security events. ",
        "SecurityEvents.ReadWrite.All": "Read and update your organization’s security events. Allows the app to read your organization’s security events. Also allows the app to update editable properties in security events. ",
        "Sites.Read.All": "Read items in all site collections. Allows the app to read documents and list items in all site collections without a signed in user. ",
        "Sites.ReadWrite.All": "Read and write items in all site collections. Allows the app to create, read, update, and delete documents and list items in all site collections without a signed in user. ",
        "Sites.Manage.All": "Have full control of all site collections. Allows the app to manage and create lists, documents, and list items in all site collections without a signed-in user. ",
        "Sites.FullControl.All": "Create, edit, and delete items and lists in all site collections. Allows the app to have full control to SharePoint sites in all site collections without a signed-in user. ",
        "User.Read.All": "Read all users' full profiles. Allows the app to read the full set of profile properties, group membership, reports and managers of other users in your organization, without a signed-in user.",
        "User.ReadWrite.All": "  Read and write all users' full profiles. Allows the app to read and write the full set of profile properties, group membership, reports and managers of other users in your organization, without a signed-in user. Also allows the app to create and delete non-administrative users. Does not allow reset of user passwords. ",
        "User.Invite.All": " Invite guest users to the organization. Allows the app to invite guest users to your organization, without a signed-in user. ",
        "User.Export.All": "Export users' data. Allows the app to export organizational users' data, without a signed-in user."
      }
    }
  },
  "tags": [
    {
      "name": "contracts.contract"
    },
    {
      "name": "devices.device"
    },
    {
      "name": "devices.extension"
    },
    {
      "name": "devices.directoryObject"
    },
    {
      "name": "directoryObjects.directoryObject"
    },
    {
      "name": "directoryRoles.directoryRole"
    },
    {
      "name": "directoryRoles.directoryObject"
    },
    {
      "name": "directoryRoleTemplates.directoryRoleTemplate"
    },
    {
      "name": "domains.domain"
    },
    {
      "name": "domains.directoryObject"
    },
    {
      "name": "domains.domainDnsRecord"
    },
    {
      "name": "drives.drive"
    },
    {
      "name": "drives.driveItem"
    },
    {
      "name": "drives.list"
    },
    {
      "name": "groupLifecyclePolicies.groupLifecyclePolicy"
    },
    {
      "name": "groups.group"
    },
    {
      "name": "groups.directoryObject"
    },
    {
      "name": "groups.calendar"
    },
    {
      "name": "groups.event"
    },
    {
      "name": "groups.conversation"
    },
    {
      "name": "groups.drive"
    },
    {
      "name": "groups.profilePhoto"
    },
    {
      "name": "groups.site"
    },
    {
      "name": "groups.conversationThread"
    },
    {
      "name": "groups.extension"
    },
    {
      "name": "groups.groupLifecyclePolicy"
    },
    {
      "name": "groups.onenote"
    },
    {
      "name": "groups.plannerGroup"
    },
    {
      "name": "groups.groupSetting"
    },
    {
      "name": "groupSettings.groupSetting"
    },
    {
      "name": "groupSettingTemplates.groupSettingTemplate"
    },
    {
      "name": "schemaExtensions.schemaExtension"
    },
    {
      "name": "shares.sharedDriveItem"
    },
    {
      "name": "shares.driveItem"
    },
    {
      "name": "shares.list"
    },
    {
      "name": "shares.listItem"
    },
    {
      "name": "shares.site"
    },
    {
      "name": "sites.site"
    },
    {
      "name": "sites.contentType"
    },
    {
      "name": "sites.drive"
    },
    {
      "name": "sites.baseItem"
    },
    {
      "name": "sites.list"
    },
    {
      "name": "sites.columnDefinition"
    },
    {
      "name": "sites.onenote"
    },
    {
      "name": "subscribedSkus.subscribedSku"
    },
    {
      "name": "subscriptions.subscription"
    },
    {
      "name": "users.user"
    },
    {
      "name": "users.managedDevice"
    },
    {
      "name": "users.managedAppRegistration"
    },
    {
      "name": "users.deviceManagementTroubleshootingEvent"
    },
    {
      "name": "users.calendar"
    },
    {
      "name": "users.calendarGroup"
    },
    {
      "name": "users.event"
    },
    {
      "name": "users.contact"
    },
    {
      "name": "users.contactFolder"
    },
    {
      "name": "users.directoryObject"
    },
    {
      "name": "users.drive"
    },
    {
      "name": "users.inferenceClassification"
    },
    {
      "name": "users.mailFolder"
    },
    {
      "name": "users.message"
    },
    {
      "name": "users.outlookUser"
    },
    {
      "name": "users.profilePhoto"
    },
    {
      "name": "users.userActivity"
    },
    {
      "name": "users.extension"
    },
    {
      "name": "users.licenseDetails"
    },
    {
      "name": "users.onenote"
    },
    {
      "name": "users.person"
    },
    {
      "name": "users.plannerUser"
    },
    {
      "name": "directory.directory"
    },
    {
      "name": "directory.directoryObject"
    },
    {
      "name": "education.educationRoot"
    },
    {
      "name": "education.educationClass"
    },
    {
      "name": "education.educationUser"
    },
    {
      "name": "education.educationSchool"
    },
    {
      "name": "invitations.invitation"
    },
    {
      "name": "invitations.user"
    },
    {
      "name": "me.user"
    },
    {
      "name": "me.managedDevice"
    },
    {
      "name": "me.managedAppRegistration"
    },
    {
      "name": "me.deviceManagementTroubleshootingEvent"
    },
    {
      "name": "me.calendar"
    },
    {
      "name": "me.calendarGroup"
    },
    {
      "name": "me.event"
    },
    {
      "name": "me.contact"
    },
    {
      "name": "me.contactFolder"
    },
    {
      "name": "me.directoryObject"
    },
    {
      "name": "me.drive"
    },
    {
      "name": "me.inferenceClassification"
    },
    {
      "name": "me.mailFolder"
    },
    {
      "name": "me.message"
    },
    {
      "name": "me.outlookUser"
    },
    {
      "name": "me.profilePhoto"
    },
    {
      "name": "me.userActivity"
    },
    {
      "name": "me.extension"
    },
    {
      "name": "me.licenseDetails"
    },
    {
      "name": "me.onenote"
    },
    {
      "name": "me.person"
    },
    {
      "name": "me.plannerUser"
    },
    {
      "name": "organization.organization"
    },
    {
      "name": "organization.extension"
    },
    {
      "name": "planner.planner"
    },
    {
      "name": "planner.plannerBucket"
    },
    {
      "name": "planner.plannerPlan"
    },
    {
      "name": "planner.plannerTask"
    },
    {
      "name": "reports.reportRoot"
    },
    {
      "name": "security.security"
    },
    {
      "name": "security.alert"
    },
    {
      "name": "groups.Functions"
    },
    {
      "name": "users.Functions"
    },
    {
      "name": "me.Functions"
    },
    {
      "name": "reports.Functions"
    },
    {
      "name": "drives.Functions"
    },
    {
      "name": "shares.Functions"
    },
    {
      "name": "directoryObjects.Actions"
    },
    {
      "name": "users.Actions"
    },
    {
      "name": "me.Actions"
    },
    {
      "name": "domains.Actions"
    },
    {
      "name": "groups.Actions"
    },
    {
      "name": "drives.Actions"
    },
    {
      "name": "shares.Actions"
    }
  ]
}