{
  "openapi": "3.0.4",
  "info": {
    "title": "OData Service for namespace microsoft.graph",
    "description": "This OData service is located at https://graph.microsoft.com/v1.0",
    "version": "1.0.1"
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0"
    }
  ],
  "paths": {
    "/contracts": {
      "get": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Get entities from contracts",
        "operationId": "contracts.contract.ListContract",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Add new entity to contracts",
        "operationId": "contracts.contract.CreateContract"
      }
    },
    "/contracts/{contract-id}": {
      "get": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Get entity from contracts by key",
        "operationId": "contracts.contract.GetContract",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Update entity in contracts",
        "operationId": "contracts.contract.UpdateContract"
      },
      "delete": {
        "tags": [
          "contracts.contract"
        ],
        "summary": "Delete entity from contracts",
        "operationId": "contracts.contract.DeleteContract"
      }
    },
    "/devices": {
      "get": {
        "tags": [
          "devices.device"
        ],
        "summary": "Get entities from devices",
        "operationId": "devices.device.ListDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Device.ReadWrite.All",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "devices.device"
        ],
        "summary": "Add new entity to devices",
        "operationId": "devices.device.CreateDevice"
      }
    },
    "/devices/{device-id}": {
      "get": {
        "tags": [
          "devices.device"
        ],
        "summary": "Get entity from devices by key",
        "operationId": "devices.device.GetDevice",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.device"
                }
              }
            },
            "links": {
              "extensions": {
                "operationId": "devices.device.GetDevice"
              },
              "registeredOwners": {
                "operationId": "devices.device.GetDevice"
              },
              "registeredUsers": {
                "operationId": "devices.device.GetDevice"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Device.ReadWrite.All",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "devices.device"
        ],
        "summary": "Update entity in devices",
        "operationId": "devices.device.UpdateDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "devices.device"
        ],
        "summary": "Delete entity from devices",
        "operationId": "devices.device.DeleteDevice",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/devices/{device-id}/extensions": {
      "get": {
        "tags": [
          "devices.extension"
        ],
        "summary": "Get extensions from devices",
        "operationId": "devices.ListExtensions"
      }
    },
    "/devices/{device-id}/extensions/{extension-id}": {
      "get": {
        "tags": [
          "devices.extension"
        ],
        "summary": "Get extensions from devices",
        "operationId": "devices.GetExtensions"
      }
    },
    "/devices/{device-id}/registeredOwners": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredOwners from devices",
        "operationId": "devices.ListRegisteredOwners"
      }
    },
    "/devices/{device-id}/registeredOwners/{directoryObject-id}": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredOwners from devices",
        "operationId": "devices.GetRegisteredOwners"
      }
    },
    "/devices/{device-id}/registeredUsers": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredUsers from devices",
        "operationId": "devices.ListRegisteredUsers"
      }
    },
    "/devices/{device-id}/registeredUsers/{directoryObject-id}": {
      "get": {
        "tags": [
          "devices.directoryObject"
        ],
        "summary": "Get registeredUsers from devices",
        "operationId": "devices.GetRegisteredUsers"
      }
    },
    "/directory": {
      "get": {
        "tags": [
          "directory.directory"
        ],
        "summary": "Get directory",
        "operationId": "directory.directory.GetDirectory"
      },
      "patch": {
        "tags": [
          "directory.directory"
        ],
        "summary": "Update directory",
        "operationId": "directory.directory.UpdateDirectory"
      }
    },
    "/directory/deletedItems": {
      "get": {
        "tags": [
          "directory.directoryObject"
        ],
        "summary": "Get deletedItems from directory",
        "operationId": "directory.ListDeletedItems"
      }
    },
    "/directory/deletedItems/{directoryObject-id}": {
      "get": {
        "tags": [
          "directory.directoryObject"
        ],
        "summary": "Get deletedItems from directory",
        "operationId": "directory.GetDeletedItems"
      }
    },
    "/directoryObjects": {
      "get": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Get entities from directoryObjects",
        "operationId": "directoryObjects.directoryObject.ListDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Add new entity to directoryObjects",
        "operationId": "directoryObjects.directoryObject.CreateDirectoryObject"
      }
    },
    "/directoryObjects/{directoryObject-id}": {
      "get": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Get entity from directoryObjects by key",
        "operationId": "directoryObjects.directoryObject.GetDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Update entity in directoryObjects",
        "operationId": "directoryObjects.directoryObject.UpdateDirectoryObject"
      },
      "delete": {
        "tags": [
          "directoryObjects.directoryObject"
        ],
        "summary": "Delete entity from directoryObjects",
        "operationId": "directoryObjects.directoryObject.DeleteDirectoryObject",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/directoryObjects/{directoryObject-id}/checkMemberGroups": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action checkMemberGroups",
        "operationId": "directoryObjects.checkMemberGroups",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          }
        ]
      }
    },
    "/directoryObjects/{directoryObject-id}/getMemberGroups": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getMemberGroups",
        "operationId": "directoryObjects.getMemberGroups",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          }
        ]
      }
    },
    "/directoryObjects/{directoryObject-id}/getMemberObjects": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getMemberObjects",
        "operationId": "directoryObjects.getMemberObjects",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "User.Read.All",
              "and",
              "Group.Read.All",
              "Directory.Read.All"
            ]
          }
        ]
      }
    },
    "/directoryObjects/{directoryObject-id}/restore": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action restore",
        "operationId": "directoryObjects.restore"
      }
    },
    "/directoryObjects/getByIds": {
      "post": {
        "tags": [
          "directoryObjects.Actions"
        ],
        "summary": "Invoke action getByIds",
        "operationId": "directoryObjects.getByIds",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All"
            ]
          }
        ]
      }
    },
    "/directoryRoles": {
      "get": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Get entities from directoryRoles",
        "operationId": "directoryRoles.directoryRole.ListDirectoryRole",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Add new entity to directoryRoles",
        "operationId": "directoryRoles.directoryRole.CreateDirectoryRole"
      }
    },
    "/directoryRoles/{directoryRole-id}": {
      "get": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Get entity from directoryRoles by key",
        "operationId": "directoryRoles.directoryRole.GetDirectoryRole",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.directoryRole"
                }
              }
            },
            "links": {
              "members": {
                "operationId": "directoryRoles.directoryRole.GetDirectoryRole"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Update entity in directoryRoles",
        "operationId": "directoryRoles.directoryRole.UpdateDirectoryRole"
      },
      "delete": {
        "tags": [
          "directoryRoles.directoryRole"
        ],
        "summary": "Delete entity from directoryRoles",
        "operationId": "directoryRoles.directoryRole.DeleteDirectoryRole"
      }
    },
    "/directoryRoles/{directoryRole-id}/members": {
      "get": {
        "tags": [
          "directoryRoles.directoryObject"
        ],
        "summary": "Get members from directoryRoles",
        "operationId": "directoryRoles.ListMembers"
      }
    },
    "/directoryRoles/{directoryRole-id}/members/{directoryObject-id}": {
      "get": {
        "tags": [
          "directoryRoles.directoryObject"
        ],
        "summary": "Get members from directoryRoles",
        "operationId": "directoryRoles.GetMembers"
      }
    },
    "/directoryRoleTemplates": {
      "get": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Get entities from directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.ListDirectoryRoleTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Add new entity to directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.CreateDirectoryRoleTemplate"
      }
    },
    "/directoryRoleTemplates/{directoryRoleTemplate-id}": {
      "get": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Get entity from directoryRoleTemplates by key",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.GetDirectoryRoleTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Update entity in directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.UpdateDirectoryRoleTemplate"
      },
      "delete": {
        "tags": [
          "directoryRoleTemplates.directoryRoleTemplate"
        ],
        "summary": "Delete entity from directoryRoleTemplates",
        "operationId": "directoryRoleTemplates.directoryRoleTemplate.DeleteDirectoryRoleTemplate"
      }
    },
    "/domains": {
      "get": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Get entities from domains",
        "operationId": "domains.domain.ListDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Add new entity to domains",
        "operationId": "domains.domain.CreateDomain"
      }
    },
    "/domains/{domain-id}": {
      "get": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Get entity from domains by key",
        "operationId": "domains.domain.GetDomain",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.domain"
                }
              }
            },
            "links": {
              "domainNameReferences": {
                "operationId": "domains.domain.GetDomain"
              },
              "serviceConfigurationRecords": {
                "operationId": "domains.domain.GetDomain"
              },
              "verificationDnsRecords": {
                "operationId": "domains.domain.GetDomain"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Update entity in domains",
        "operationId": "domains.domain.UpdateDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Domain.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "domains.domain"
        ],
        "summary": "Delete entity from domains",
        "operationId": "domains.domain.DeleteDomain",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Domain.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/domains/{domain-id}/domainNameReferences": {
      "get": {
        "tags": [
          "domains.directoryObject"
        ],
        "summary": "Get domainNameReferences from domains",
        "operationId": "domains.ListDomainNameReferences"
      }
    },
    "/domains/{domain-id}/domainNameReferences/{directoryObject-id}": {
      "get": {
        "tags": [
          "domains.directoryObject"
        ],
        "summary": "Get domainNameReferences from domains",
        "operationId": "domains.GetDomainNameReferences"
      }
    },
    "/domains/{domain-id}/verify": {
      "post": {
        "tags": [
          "domains.Actions"
        ],
        "summary": "Invoke action verify",
        "operationId": "domains.verify",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Domain.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/domains/{domain-id}/serviceConfigurationRecords": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get serviceConfigurationRecords from domains",
        "operationId": "domains.ListServiceConfigurationRecords"
      }
    },
    "/domains/{domain-id}/serviceConfigurationRecords/{domainDnsRecord-id}": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get serviceConfigurationRecords from domains",
        "operationId": "domains.GetServiceConfigurationRecords"
      }
    },
    "/domains/{domain-id}/verificationDnsRecords": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get verificationDnsRecords from domains",
        "operationId": "domains.ListVerificationDnsRecords"
      }
    },
    "/domains/{domain-id}/verificationDnsRecords/{domainDnsRecord-id}": {
      "get": {
        "tags": [
          "domains.domainDnsRecord"
        ],
        "summary": "Get verificationDnsRecords from domains",
        "operationId": "domains.GetVerificationDnsRecords"
      }
    },
    "/drives": {
      "get": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Get entities from drives",
        "operationId": "drives.drive.ListDrive"
      },
      "post": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Add new entity to drives",
        "operationId": "drives.drive.CreateDrive"
      }
    },
    "/drives/{drive-id}": {
      "get": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Get entity from drives by key",
        "operationId": "drives.drive.GetDrive",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.drive"
                }
              }
            },
            "links": {
              "items": {
                "operationId": "drives.drive.GetDrive"
              },
              "root": {
                "operationId": "drives.drive.GetDrive"
              },
              "special": {
                "operationId": "drives.drive.GetDrive"
              },
              "list": {
                "operationId": "drives.drive.GetDrive"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        }
      },
      "patch": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Update entity in drives",
        "operationId": "drives.drive.UpdateDrive"
      },
      "delete": {
        "tags": [
          "drives.drive"
        ],
        "summary": "Delete entity from drives",
        "operationId": "drives.drive.DeleteDrive"
      }
    },
    "/drives/{drive-id}/items": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get items from drives",
        "operationId": "drives.ListItems"
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get items from drives",
        "operationId": "drives.GetItems"
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "drives.items.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "drives.items.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.items.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "drives.items.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "drives.items.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "drives.items.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{driveItem-id}/search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.items.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/list": {
      "get": {
        "tags": [
          "drives.list"
        ],
        "summary": "Get list from drives",
        "operationId": "drives.GetList"
      }
    },
    "/drives/{drive-id}/recent()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "This method returns a collection of [DriveItem](../resources/driveitem.md) resources for items which the owner of the drive has recently accessed.",
        "operationId": "drives.recent.f75f",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "In addition to searching for items within a drive, your app can search more broadly to include items shared with the current user.\r\nTo broaden the search scope, use the **search** method on the [Drive](../resources/drive.md) resource.",
        "operationId": "drives.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/sharedWithMe()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "This returns a collection of [DriveItem](../resources/driveitem.md) resources which contain the DriveItem resources shared with the owner of the drive.\r\nIn this example, since the drive is the user's default drive, this returns items shared with the signed in user.",
        "operationId": "drives.sharedWithMe.29d5",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get root from drives",
        "operationId": "drives.GetRoot"
      }
    },
    "/drives/{drive-id}/root/copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "drives.root.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "drives.root.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.root.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "drives.root.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "drives.root.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "drives.root.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.root.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get special from drives",
        "operationId": "drives.ListSpecial"
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}": {
      "get": {
        "tags": [
          "drives.driveItem"
        ],
        "summary": "Get special from drives",
        "operationId": "drives.GetSpecial"
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/copy": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "drives.special.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/createLink": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "drives.special.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/createUploadSession": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "drives.special.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/delta()": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "drives.special.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/delta(token={token})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "drives.special.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/invite": {
      "post": {
        "tags": [
          "drives.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "drives.special.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/drives/{drive-id}/special/{driveItem-id}/search(q={q})": {
      "get": {
        "tags": [
          "drives.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "drives.special.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/education": {
      "get": {
        "tags": [
          "education.educationRoot"
        ],
        "summary": "Here is a JSON representation of the resource.",
        "operationId": "education.educationRoot.GetEducationRoot"
      },
      "patch": {
        "tags": [
          "education.educationRoot"
        ],
        "summary": "Update education",
        "operationId": "education.educationRoot.UpdateEducationRoot"
      }
    },
    "/education/classes": {
      "get": {
        "tags": [
          "education.educationClass"
        ],
        "summary": "Get classes from education",
        "operationId": "education.ListClasses"
      }
    },
    "/education/classes/{educationClass-id}": {
      "get": {
        "tags": [
          "education.educationClass"
        ],
        "summary": "Get classes from education",
        "operationId": "education.GetClasses"
      }
    },
    "/education/me": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get me from education",
        "operationId": "education.GetMe"
      }
    },
    "/education/schools": {
      "get": {
        "tags": [
          "education.educationSchool"
        ],
        "summary": "Get schools from education",
        "operationId": "education.ListSchools"
      }
    },
    "/education/schools/{educationSchool-id}": {
      "get": {
        "tags": [
          "education.educationSchool"
        ],
        "summary": "Get schools from education",
        "operationId": "education.GetSchools"
      }
    },
    "/education/users": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get users from education",
        "operationId": "education.ListUsers"
      }
    },
    "/education/users/{educationUser-id}": {
      "get": {
        "tags": [
          "education.educationUser"
        ],
        "summary": "Get users from education",
        "operationId": "education.GetUsers"
      }
    },
    "/groupLifecyclePolicies": {
      "get": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Get entities from groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.ListGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Add new entity to groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.CreateGroupLifecyclePolicy"
      }
    },
    "/groupLifecyclePolicies/{groupLifecyclePolicy-id}": {
      "get": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Get entity from groupLifecyclePolicies by key",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.GetGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Update entity in groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.UpdateGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groupLifecyclePolicies.groupLifecyclePolicy"
        ],
        "summary": "Delete entity from groupLifecyclePolicies",
        "operationId": "groupLifecyclePolicies.groupLifecyclePolicy.DeleteGroupLifecyclePolicy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups": {
      "get": {
        "tags": [
          "groups.group"
        ],
        "summary": "Get entities from groups",
        "operationId": "groups.group.ListGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groups.group"
        ],
        "summary": "Add new entity to groups",
        "operationId": "groups.group.CreateGroup"
      }
    },
    "/groups/{group-id}": {
      "get": {
        "tags": [
          "groups.group"
        ],
        "summary": "Get entity from groups by key",
        "operationId": "groups.group.GetGroup",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.group"
                }
              }
            },
            "links": {
              "acceptedSenders": {
                "operationId": "groups.group.GetGroup"
              },
              "calendar": {
                "operationId": "groups.group.GetGroup"
              },
              "calendarView": {
                "operationId": "groups.group.GetGroup"
              },
              "conversations": {
                "operationId": "groups.group.GetGroup"
              },
              "createdOnBehalfOf": {
                "operationId": "groups.group.GetGroup"
              },
              "drive": {
                "operationId": "groups.group.GetGroup"
              },
              "events": {
                "operationId": "groups.group.GetGroup"
              },
              "memberOf": {
                "operationId": "groups.group.GetGroup"
              },
              "members": {
                "operationId": "groups.group.GetGroup"
              },
              "owners": {
                "operationId": "groups.group.GetGroup"
              },
              "photo": {
                "operationId": "groups.group.GetGroup"
              },
              "rejectedSenders": {
                "operationId": "groups.group.GetGroup"
              },
              "sites": {
                "operationId": "groups.group.GetGroup"
              },
              "threads": {
                "operationId": "groups.group.GetGroup"
              },
              "drives": {
                "operationId": "groups.group.GetGroup"
              },
              "extensions": {
                "operationId": "groups.group.GetGroup"
              },
              "groupLifecyclePolicies": {
                "operationId": "groups.group.GetGroup"
              },
              "onenote": {
                "operationId": "groups.group.GetGroup"
              },
              "photos": {
                "operationId": "groups.group.GetGroup"
              },
              "planner": {
                "operationId": "groups.group.GetGroup"
              },
              "settings": {
                "operationId": "groups.group.GetGroup"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groups.group"
        ],
        "summary": "Update entity in groups",
        "operationId": "groups.group.UpdateGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groups.group"
        ],
        "summary": "Delete entity from groups",
        "operationId": "groups.group.DeleteGroup",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/acceptedSenders": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get acceptedSenders from groups",
        "operationId": "groups.ListAcceptedSenders"
      }
    },
    "/groups/{group-id}/acceptedSenders/{directoryObject-id}": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get acceptedSenders from groups",
        "operationId": "groups.GetAcceptedSenders"
      }
    },
    "/groups/{group-id}/calendar": {
      "get": {
        "tags": [
          "groups.calendar"
        ],
        "summary": "Get calendar from groups",
        "operationId": "groups.GetCalendar"
      }
    },
    "/groups/{group-id}/calendarView": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get calendarView from groups",
        "operationId": "groups.ListCalendarView"
      }
    },
    "/groups/{group-id}/calendarView/{event-id}": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get calendarView from groups",
        "operationId": "groups.GetCalendarView"
      }
    },
    "/groups/{group-id}/calendarView/{event-id}/accept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.calendarView.accept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/calendarView/{event-id}/decline": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.calendarView.decline",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/calendarView/{event-id}/dismissReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.calendarView.dismissReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/calendarView/{event-id}/snoozeReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.calendarView.snoozeReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/calendarView/{event-id}/tentativelyAccept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.calendarView.tentativelyAccept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/calendarView/delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.calendarView.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.Read"
            ]
          },
          {
            "Application": [
              "Calendars.Read"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/conversations": {
      "get": {
        "tags": [
          "groups.conversation"
        ],
        "summary": "Get conversations from groups",
        "operationId": "groups.ListConversations"
      }
    },
    "/groups/{group-id}/conversations/{conversation-id}": {
      "get": {
        "tags": [
          "groups.conversation"
        ],
        "summary": "Get conversations from groups",
        "operationId": "groups.GetConversations"
      }
    },
    "/groups/{group-id}/createdOnBehalfOf": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get createdOnBehalfOf from groups",
        "operationId": "groups.GetCreatedOnBehalfOf"
      }
    },
    "/groups/{group-id}/drive": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drive from groups",
        "operationId": "groups.GetDrive"
      }
    },
    "/groups/{group-id}/drives": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drives from groups",
        "operationId": "groups.ListDrives"
      }
    },
    "/groups/{group-id}/drives/{drive-id}": {
      "get": {
        "tags": [
          "groups.drive"
        ],
        "summary": "Get drives from groups",
        "operationId": "groups.GetDrives"
      }
    },
    "/groups/{group-id}/events": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get events from groups",
        "operationId": "groups.ListEvents"
      }
    },
    "/groups/{group-id}/events/{event-id}": {
      "get": {
        "tags": [
          "groups.event"
        ],
        "summary": "Get events from groups",
        "operationId": "groups.GetEvents"
      }
    },
    "/groups/{group-id}/events/{event-id}/accept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.events.accept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/events/{event-id}/decline": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.events.decline",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/events/{event-id}/dismissReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.events.dismissReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/events/{event-id}/snoozeReminder": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.events.snoozeReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/events/{event-id}/tentativelyAccept": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.events.tentativelyAccept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/events/delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.events.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.Read"
            ]
          },
          {
            "Application": [
              "Calendars.Read"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/extensions": {
      "get": {
        "tags": [
          "groups.extension"
        ],
        "summary": "Get extensions from groups",
        "operationId": "groups.ListExtensions"
      }
    },
    "/groups/{group-id}/extensions/{extension-id}": {
      "get": {
        "tags": [
          "groups.extension"
        ],
        "summary": "Get extensions from groups",
        "operationId": "groups.GetExtensions"
      }
    },
    "/groups/{group-id}/groupLifecyclePolicies": {
      "get": {
        "tags": [
          "groups.groupLifecyclePolicy"
        ],
        "summary": "Get groupLifecyclePolicies from groups",
        "operationId": "groups.ListGroupLifecyclePolicies"
      }
    },
    "/groups/{group-id}/groupLifecyclePolicies/{groupLifecyclePolicy-id}": {
      "get": {
        "tags": [
          "groups.groupLifecyclePolicy"
        ],
        "summary": "Get groupLifecyclePolicies from groups",
        "operationId": "groups.GetGroupLifecyclePolicies"
      }
    },
    "/groups/{group-id}/memberOf": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get memberOf from groups",
        "operationId": "groups.ListMemberOf"
      }
    },
    "/groups/{group-id}/memberOf/{directoryObject-id}": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get memberOf from groups",
        "operationId": "groups.GetMemberOf"
      }
    },
    "/groups/{group-id}/members": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get members from groups",
        "operationId": "groups.ListMembers"
      }
    },
    "/groups/{group-id}/members/{directoryObject-id}": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get members from groups",
        "operationId": "groups.GetMembers"
      }
    },
    "/groups/{group-id}/addFavorite": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action addFavorite",
        "operationId": "groups.addFavorite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/removeFavorite": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action removeFavorite",
        "operationId": "groups.removeFavorite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/renew": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action renew",
        "operationId": "groups.renew",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All",
              "or",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/resetUnseenCount": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action resetUnseenCount",
        "operationId": "groups.resetUnseenCount",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/subscribeByMail": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action subscribeByMail",
        "operationId": "groups.subscribeByMail",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/unsubscribeByMail": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action unsubscribeByMail",
        "operationId": "groups.unsubscribeByMail",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/{group-id}/onenote": {
      "get": {
        "tags": [
          "groups.onenote"
        ],
        "summary": "Get onenote from groups",
        "operationId": "groups.GetOnenote"
      }
    },
    "/groups/{group-id}/owners": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get owners from groups",
        "operationId": "groups.ListOwners"
      }
    },
    "/groups/{group-id}/owners/{directoryObject-id}": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get owners from groups",
        "operationId": "groups.GetOwners"
      }
    },
    "/groups/{group-id}/photo": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photo from groups",
        "operationId": "groups.GetPhoto"
      }
    },
    "/groups/{group-id}/photos": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photos from groups",
        "operationId": "groups.ListPhotos"
      }
    },
    "/groups/{group-id}/photos/{profilePhoto-id}": {
      "get": {
        "tags": [
          "groups.profilePhoto"
        ],
        "summary": "Get photos from groups",
        "operationId": "groups.GetPhotos"
      }
    },
    "/groups/{group-id}/planner": {
      "get": {
        "tags": [
          "groups.plannerGroup"
        ],
        "summary": "Get planner from groups",
        "operationId": "groups.GetPlanner"
      }
    },
    "/groups/{group-id}/rejectedSenders": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get rejectedSenders from groups",
        "operationId": "groups.ListRejectedSenders"
      }
    },
    "/groups/{group-id}/rejectedSenders/{directoryObject-id}": {
      "get": {
        "tags": [
          "groups.directoryObject"
        ],
        "summary": "Get rejectedSenders from groups",
        "operationId": "groups.GetRejectedSenders"
      }
    },
    "/groups/{group-id}/settings": {
      "get": {
        "tags": [
          "groups.groupSetting"
        ],
        "summary": "Get settings from groups",
        "operationId": "groups.ListSettings"
      }
    },
    "/groups/{group-id}/settings/{groupSetting-id}": {
      "get": {
        "tags": [
          "groups.groupSetting"
        ],
        "summary": "Get settings from groups",
        "operationId": "groups.GetSettings"
      }
    },
    "/groups/{group-id}/sites": {
      "get": {
        "tags": [
          "groups.site"
        ],
        "summary": "Get sites from groups",
        "operationId": "groups.ListSites"
      }
    },
    "/groups/{group-id}/sites/{site-id}": {
      "get": {
        "tags": [
          "groups.site"
        ],
        "summary": "Get sites from groups",
        "operationId": "groups.GetSites"
      }
    },
    "/groups/{group-id}/threads": {
      "get": {
        "tags": [
          "groups.conversationThread"
        ],
        "summary": "Get threads from groups",
        "operationId": "groups.ListThreads"
      }
    },
    "/groups/{group-id}/threads/{conversationThread-id}": {
      "get": {
        "tags": [
          "groups.conversationThread"
        ],
        "summary": "Get threads from groups",
        "operationId": "groups.GetThreads"
      }
    },
    "/groups/{group-id}/threads/{conversationThread-id}/reply": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "groups.threads.reply",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groups/delta()": {
      "get": {
        "tags": [
          "groups.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "groups.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Group.Read.All",
              "Group.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groupSettings": {
      "get": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Get entities from groupSettings",
        "operationId": "groupSettings.groupSetting.ListGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Add new entity to groupSettings",
        "operationId": "groupSettings.groupSetting.CreateGroupSetting"
      }
    },
    "/groupSettings/{groupSetting-id}": {
      "get": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Get entity from groupSettings by key",
        "operationId": "groupSettings.groupSetting.GetGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Update entity in groupSettings",
        "operationId": "groupSettings.groupSetting.UpdateGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "groupSettings.groupSetting"
        ],
        "summary": "Delete entity from groupSettings",
        "operationId": "groupSettings.groupSetting.DeleteGroupSetting",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/groupSettingTemplates": {
      "get": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Get entities from groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.ListGroupSettingTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Add new entity to groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.CreateGroupSettingTemplate"
      }
    },
    "/groupSettingTemplates/{groupSettingTemplate-id}": {
      "get": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Get entity from groupSettingTemplates by key",
        "operationId": "groupSettingTemplates.groupSettingTemplate.GetGroupSettingTemplate",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.Read.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Update entity in groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.UpdateGroupSettingTemplate"
      },
      "delete": {
        "tags": [
          "groupSettingTemplates.groupSettingTemplate"
        ],
        "summary": "Delete entity from groupSettingTemplates",
        "operationId": "groupSettingTemplates.groupSettingTemplate.DeleteGroupSettingTemplate"
      }
    },
    "/invitations": {
      "get": {
        "tags": [
          "invitations.invitation"
        ],
        "summary": "Get invitations",
        "operationId": "invitations.invitation.GetInvitation"
      },
      "patch": {
        "tags": [
          "invitations.invitation"
        ],
        "summary": "Update invitations",
        "operationId": "invitations.invitation.UpdateInvitation"
      }
    },
    "/invitations/invitedUser": {
      "get": {
        "tags": [
          "invitations.user"
        ],
        "summary": "Get invitedUser from invitations",
        "operationId": "invitations.GetInvitedUser"
      }
    },
    "/me": {
      "get": {
        "tags": [
          "me.user"
        ],
        "summary": "Get me",
        "operationId": "me.user.GetUser"
      },
      "patch": {
        "tags": [
          "me.user"
        ],
        "summary": "Update me",
        "operationId": "me.user.UpdateUser",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.ReadWrite",
              "User.ReadWrite.All",
              "Directory.ReadWrite.All",
              "Directory.AccessAsUser.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "User.ReadWrite"
            ]
          },
          {
            "Application": [
              "User.ReadWrite.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/me/activities": {
      "get": {
        "tags": [
          "me.userActivity"
        ],
        "summary": "Get activities from me",
        "operationId": "me.ListActivities"
      }
    },
    "/me/activities/{userActivity-id}": {
      "get": {
        "tags": [
          "me.userActivity"
        ],
        "summary": "Get activities from me",
        "operationId": "me.GetActivities"
      }
    },
    "/me/activities/recent()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function recent",
        "operationId": "me.activities.recent.f75f",
        "security": [
          {
            "Delegated (work or school account)": [
              "UserActivity.ReadWrite.CreatedByApp"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "UserActivity.ReadWrite.CreatedByApp"
            ]
          }
        ]
      }
    },
    "/me/calendar": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendar from me",
        "operationId": "me.GetCalendar"
      }
    },
    "/me/calendarGroups": {
      "get": {
        "tags": [
          "me.calendarGroup"
        ],
        "summary": "Get calendarGroups from me",
        "operationId": "me.ListCalendarGroups"
      }
    },
    "/me/calendarGroups/{calendarGroup-id}": {
      "get": {
        "tags": [
          "me.calendarGroup"
        ],
        "summary": "Get calendarGroups from me",
        "operationId": "me.GetCalendarGroups"
      }
    },
    "/me/calendars": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendars from me",
        "operationId": "me.ListCalendars"
      }
    },
    "/me/calendars/{calendar-id}": {
      "get": {
        "tags": [
          "me.calendar"
        ],
        "summary": "Get calendars from me",
        "operationId": "me.GetCalendars"
      }
    },
    "/me/calendarView": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get calendarView from me",
        "operationId": "me.ListCalendarView"
      }
    },
    "/me/calendarView/{event-id}": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get calendarView from me",
        "operationId": "me.GetCalendarView"
      }
    },
    "/me/calendarView/{event-id}/accept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.calendarView.accept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/calendarView/{event-id}/decline": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.calendarView.decline",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/calendarView/{event-id}/dismissReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.calendarView.dismissReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/calendarView/{event-id}/snoozeReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.calendarView.snoozeReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/calendarView/{event-id}/tentativelyAccept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.calendarView.tentativelyAccept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/calendarView/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.calendarView.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.Read"
            ]
          },
          {
            "Application": [
              "Calendars.Read"
            ]
          }
        ]
      }
    },
    "/me/contactFolders": {
      "get": {
        "tags": [
          "me.contactFolder"
        ],
        "summary": "Get contactFolders from me",
        "operationId": "me.ListContactFolders"
      }
    },
    "/me/contactFolders/{contactFolder-id}": {
      "get": {
        "tags": [
          "me.contactFolder"
        ],
        "summary": "Get contactFolders from me",
        "operationId": "me.GetContactFolders"
      }
    },
    "/me/contactFolders/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.contactFolders.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          },
          {
            "Application": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/contacts": {
      "get": {
        "tags": [
          "me.contact"
        ],
        "summary": "Get contacts from me",
        "operationId": "me.ListContacts"
      }
    },
    "/me/contacts/{contact-id}": {
      "get": {
        "tags": [
          "me.contact"
        ],
        "summary": "Get contacts from me",
        "operationId": "me.GetContacts"
      }
    },
    "/me/contacts/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.contacts.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          },
          {
            "Application": [
              "Contacts.Read",
              "Contacts.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/createdObjects": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get createdObjects from me",
        "operationId": "me.ListCreatedObjects"
      }
    },
    "/me/createdObjects/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get createdObjects from me",
        "operationId": "me.GetCreatedObjects"
      }
    },
    "/me/deviceManagementTroubleshootingEvents": {
      "get": {
        "tags": [
          "me.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from me",
        "operationId": "me.ListDeviceManagementTroubleshootingEvents"
      }
    },
    "/me/deviceManagementTroubleshootingEvents/{deviceManagementTroubleshootingEvent-id}": {
      "get": {
        "tags": [
          "me.deviceManagementTroubleshootingEvent"
        ],
        "summary": "Get deviceManagementTroubleshootingEvents from me",
        "operationId": "me.GetDeviceManagementTroubleshootingEvents"
      }
    },
    "/me/directReports": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get directReports from me",
        "operationId": "me.ListDirectReports"
      }
    },
    "/me/directReports/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get directReports from me",
        "operationId": "me.GetDirectReports"
      }
    },
    "/me/drive": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drive from me",
        "operationId": "me.GetDrive"
      }
    },
    "/me/drives": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drives from me",
        "operationId": "me.ListDrives"
      }
    },
    "/me/drives/{drive-id}": {
      "get": {
        "tags": [
          "me.drive"
        ],
        "summary": "Get drives from me",
        "operationId": "me.GetDrives"
      }
    },
    "/me/events": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get events from me",
        "operationId": "me.ListEvents"
      }
    },
    "/me/events/{event-id}": {
      "get": {
        "tags": [
          "me.event"
        ],
        "summary": "Get events from me",
        "operationId": "me.GetEvents"
      }
    },
    "/me/events/{event-id}/accept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.events.accept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/events/{event-id}/decline": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.events.decline",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/events/{event-id}/dismissReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.events.dismissReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/events/{event-id}/snoozeReminder": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.events.snoozeReminder",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/events/{event-id}/tentativelyAccept": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.events.tentativelyAccept",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/events/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.events.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.Read"
            ]
          },
          {
            "Application": [
              "Calendars.Read"
            ]
          }
        ]
      }
    },
    "/me/extensions": {
      "get": {
        "tags": [
          "me.extension"
        ],
        "summary": "Get extensions from me",
        "operationId": "me.ListExtensions"
      }
    },
    "/me/extensions/{extension-id}": {
      "get": {
        "tags": [
          "me.extension"
        ],
        "summary": "Get extensions from me",
        "operationId": "me.GetExtensions"
      }
    },
    "/me/inferenceClassification": {
      "get": {
        "tags": [
          "me.inferenceClassification"
        ],
        "summary": "Get inferenceClassification from me",
        "operationId": "me.GetInferenceClassification"
      }
    },
    "/me/licenseDetails": {
      "get": {
        "tags": [
          "me.licenseDetails"
        ],
        "summary": "Get licenseDetails from me",
        "operationId": "me.ListLicenseDetails"
      }
    },
    "/me/licenseDetails/{licenseDetails-id}": {
      "get": {
        "tags": [
          "me.licenseDetails"
        ],
        "summary": "Get licenseDetails from me",
        "operationId": "me.GetLicenseDetails"
      }
    },
    "/me/mailFolders": {
      "get": {
        "tags": [
          "me.mailFolder"
        ],
        "summary": "Get mailFolders from me",
        "operationId": "me.ListMailFolders"
      }
    },
    "/me/mailFolders/{mailFolder-id}": {
      "get": {
        "tags": [
          "me.mailFolder"
        ],
        "summary": "Get mailFolders from me",
        "operationId": "me.GetMailFolders"
      }
    },
    "/me/mailFolders/{mailFolder-id}/copy": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.mailFolders.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/mailFolders/{mailFolder-id}/move": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.mailFolders.move",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/mailFolders/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.mailFolders.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/managedAppRegistrations": {
      "get": {
        "tags": [
          "me.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from me",
        "operationId": "me.ListManagedAppRegistrations"
      }
    },
    "/me/managedAppRegistrations/{managedAppRegistration-id}": {
      "get": {
        "tags": [
          "me.managedAppRegistration"
        ],
        "summary": "Get managedAppRegistrations from me",
        "operationId": "me.GetManagedAppRegistrations"
      }
    },
    "/me/managedDevices": {
      "get": {
        "tags": [
          "me.managedDevice"
        ],
        "summary": "Get managedDevices from me",
        "operationId": "me.ListManagedDevices"
      }
    },
    "/me/managedDevices/{managedDevice-id}": {
      "get": {
        "tags": [
          "me.managedDevice"
        ],
        "summary": "Get managedDevices from me",
        "operationId": "me.GetManagedDevices"
      }
    },
    "/me/manager": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get manager from me",
        "operationId": "me.GetManager"
      }
    },
    "/me/memberOf": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get memberOf from me",
        "operationId": "me.ListMemberOf"
      }
    },
    "/me/memberOf/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get memberOf from me",
        "operationId": "me.GetMemberOf"
      }
    },
    "/me/messages": {
      "get": {
        "tags": [
          "me.message"
        ],
        "summary": "Get messages from me",
        "operationId": "me.ListMessages"
      }
    },
    "/me/messages/{message-id}": {
      "get": {
        "tags": [
          "me.message"
        ],
        "summary": "Get messages from me",
        "operationId": "me.GetMessages"
      }
    },
    "/me/messages/{message-id}/copy": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createForward": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.createForward",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createReply": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.createReply",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createReplyAll": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.createReplyAll",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/forward": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.forward",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Send"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Send"
            ]
          },
          {
            "Application": [
              "Mail.Send"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/move": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.move",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/reply": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.reply",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Send"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Send"
            ]
          },
          {
            "Application": [
              "Mail.Send"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/replyAll": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.messages.replyAll",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Send"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Send"
            ]
          },
          {
            "Application": [
              "Mail.Send"
            ]
          }
        ]
      }
    },
    "/me/messages/{message-id}/send": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "The following example shows how to call this API.",
        "operationId": "me.messages.send",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Send"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Send"
            ]
          },
          {
            "Application": [
              "Mail.Send"
            ]
          }
        ]
      }
    },
    "/me/messages/delta()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function delta",
        "operationId": "me.messages.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          },
          {
            "Application": [
              "Mail.Read",
              "Mail.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/assignLicense": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.assignLicense",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.ReadWrite.All",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "User.ReadWrite.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/me/findMeetingTimes": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Notice that the request specifies time in the PST time zone, and the response returns meeting time suggestions in UTC, by default. You can use the `Prefer: outlook.timezone` request \r\nheader to specify PST as well for the time values in the response.",
        "operationId": "me.findMeetingTimes",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read.Shared",
              "Calendars.ReadWrite.Shared"
            ]
          }
        ]
      }
    },
    "/me/getMailTips": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Invoke action getMailTips",
        "operationId": "me.getMailTips",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Read",
              "Mail.Read.Shared"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Read"
            ]
          },
          {
            "Application": [
              "Mail.Read"
            ]
          }
        ]
      }
    },
    "/me/reminderView(endDateTime={endDateTime},startDateTime={startDateTime})": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.reminderView.d02b",
        "security": [
          {
            "Delegated (work or school account)": [
              "Calendars.Read",
              "Calendars.ReadWrite"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Calendars.Read",
              "Calendars.ReadWrite"
            ]
          },
          {
            "Application": [
              "Calendars.Read",
              "Calendars.ReadWrite"
            ]
          }
        ]
      }
    },
    "/me/sendMail": {
      "post": {
        "tags": [
          "me.Actions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.sendMail",
        "security": [
          {
            "Delegated (work or school account)": [
              "Mail.Send"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Mail.Send"
            ]
          },
          {
            "Application": [
              "Mail.Send"
            ]
          }
        ]
      }
    },
    "/me/onenote": {
      "get": {
        "tags": [
          "me.onenote"
        ],
        "summary": "Get onenote from me",
        "operationId": "me.GetOnenote"
      }
    },
    "/me/outlook": {
      "get": {
        "tags": [
          "me.outlookUser"
        ],
        "summary": "Get outlook from me",
        "operationId": "me.GetOutlook"
      }
    },
    "/me/outlook/supportedLanguages()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Here is an example of how to call this API.",
        "operationId": "me.outlook.supportedLanguages.7d99",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read",
              "User.ReadBasic.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "User.Read"
            ]
          },
          {
            "Application": [
              "User.Read.All"
            ]
          }
        ]
      }
    },
    "/me/outlook/supportedTimeZones()": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "me.outlook.supportedTimeZones.4c5b",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read",
              "User.ReadBasic.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "User.Read"
            ]
          },
          {
            "Application": [
              "User.Read.All"
            ]
          }
        ]
      }
    },
    "/me/outlook/supportedTimeZones(TimeZoneStandard={TimeZoneStandard})": {
      "get": {
        "tags": [
          "me.Functions"
        ],
        "summary": "Invoke function supportedTimeZones",
        "operationId": "me.outlook.supportedTimeZones.cfd8",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read",
              "User.ReadBasic.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "User.Read"
            ]
          },
          {
            "Application": [
              "User.Read.All"
            ]
          }
        ]
      }
    },
    "/me/ownedDevices": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedDevices from me",
        "operationId": "me.ListOwnedDevices"
      }
    },
    "/me/ownedDevices/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedDevices from me",
        "operationId": "me.GetOwnedDevices"
      }
    },
    "/me/ownedObjects": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedObjects from me",
        "operationId": "me.ListOwnedObjects"
      }
    },
    "/me/ownedObjects/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get ownedObjects from me",
        "operationId": "me.GetOwnedObjects"
      }
    },
    "/me/people": {
      "get": {
        "tags": [
          "me.person"
        ],
        "summary": "Get people from me",
        "operationId": "me.ListPeople"
      }
    },
    "/me/people/{person-id}": {
      "get": {
        "tags": [
          "me.person"
        ],
        "summary": "Get people from me",
        "operationId": "me.GetPeople"
      }
    },
    "/me/photo": {
      "get": {
        "tags": [
          "me.profilePhoto"
        ],
        "summary": "Get photo from me",
        "operationId": "me.GetPhoto"
      }
    },
    "/me/planner": {
      "get": {
        "tags": [
          "me.plannerUser"
        ],
        "summary": "Get planner from me",
        "operationId": "me.GetPlanner"
      }
    },
    "/me/registeredDevices": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get registeredDevices from me",
        "operationId": "me.ListRegisteredDevices"
      }
    },
    "/me/registeredDevices/{directoryObject-id}": {
      "get": {
        "tags": [
          "me.directoryObject"
        ],
        "summary": "Get registeredDevices from me",
        "operationId": "me.GetRegisteredDevices"
      }
    },
    "/organization": {
      "get": {
        "tags": [
          "organization.organization"
        ],
        "summary": "Get organization",
        "operationId": "organization.organization.GetOrganization",
        "security": [
          {
            "Delegated (work or school account)": [
              "User.Read",
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Directory.Read.All",
              "Directory.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "organization.organization"
        ],
        "summary": "Update organization",
        "operationId": "organization.organization.UpdateOrganization",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/organization/extensions": {
      "get": {
        "tags": [
          "organization.extension"
        ],
        "summary": "Get extensions from organization",
        "operationId": "organization.ListExtensions"
      }
    },
    "/organization/extensions/{extension-id}": {
      "get": {
        "tags": [
          "organization.extension"
        ],
        "summary": "Get extensions from organization",
        "operationId": "organization.GetExtensions"
      }
    },
    "/planner": {
      "get": {
        "tags": [
          "planner.planner"
        ],
        "summary": "The **planner** resource is available at the root of the graph.",
        "operationId": "planner.planner.GetPlanner"
      },
      "patch": {
        "tags": [
          "planner.planner"
        ],
        "summary": "Update planner",
        "operationId": "planner.planner.UpdatePlanner"
      }
    },
    "/planner/buckets": {
      "get": {
        "tags": [
          "planner.plannerBucket"
        ],
        "summary": "Get buckets from planner",
        "operationId": "planner.ListBuckets"
      }
    },
    "/planner/buckets/{plannerBucket-id}": {
      "get": {
        "tags": [
          "planner.plannerBucket"
        ],
        "summary": "Get buckets from planner",
        "operationId": "planner.GetBuckets"
      }
    },
    "/planner/plans": {
      "get": {
        "tags": [
          "planner.plannerPlan"
        ],
        "summary": "Get plans from planner",
        "operationId": "planner.ListPlans"
      }
    },
    "/planner/plans/{plannerPlan-id}": {
      "get": {
        "tags": [
          "planner.plannerPlan"
        ],
        "summary": "Get plans from planner",
        "operationId": "planner.GetPlans"
      }
    },
    "/planner/tasks": {
      "get": {
        "tags": [
          "planner.plannerTask"
        ],
        "summary": "Get tasks from planner",
        "operationId": "planner.ListTasks"
      }
    },
    "/planner/tasks/{plannerTask-id}": {
      "get": {
        "tags": [
          "planner.plannerTask"
        ],
        "summary": "Get tasks from planner",
        "operationId": "planner.GetTasks"
      }
    },
    "/reports": {
      "get": {
        "tags": [
          "reports.reportRoot"
        ],
        "summary": "Get reports",
        "operationId": "reports.reportRoot.GetReportRoot"
      },
      "patch": {
        "tags": [
          "reports.reportRoot"
        ],
        "summary": "Update reports",
        "operationId": "reports.reportRoot.UpdateReportRoot"
      }
    },
    "/reports/getEmailActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityCounts",
        "operationId": "reports.getEmailActivityCounts.d2c9",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserCounts",
        "operationId": "reports.getEmailActivityUserCounts.67ae",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserDetail",
        "operationId": "reports.getEmailActivityUserDetail.35e0",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailActivityUserDetail",
        "operationId": "reports.getEmailActivityUserDetail.ae84",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailAppUsageAppsUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageAppsUserCounts",
        "operationId": "reports.getEmailAppUsageAppsUserCounts.807c",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailAppUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserCounts",
        "operationId": "reports.getEmailAppUsageUserCounts.6fd2",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailAppUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserDetail",
        "operationId": "reports.getEmailAppUsageUserDetail.8c90",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailAppUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageUserDetail",
        "operationId": "reports.getEmailAppUsageUserDetail.a73d",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getEmailAppUsageVersionsUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getEmailAppUsageVersionsUserCounts",
        "operationId": "reports.getEmailAppUsageVersionsUserCounts.f73b",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getMailboxUsageDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageDetail",
        "operationId": "reports.getMailboxUsageDetail.6ef8",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getMailboxUsageMailboxCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageMailboxCounts",
        "operationId": "reports.getMailboxUsageMailboxCounts.1ae9",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getMailboxUsageQuotaStatusMailboxCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageQuotaStatusMailboxCounts",
        "operationId": "reports.getMailboxUsageQuotaStatusMailboxCounts.b080",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getMailboxUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getMailboxUsageStorage",
        "operationId": "reports.getMailboxUsageStorage.fdb0",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActivationCounts()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationCounts",
        "operationId": "reports.getOffice365ActivationCounts.dd57",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActivationsUserCounts()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationsUserCounts",
        "operationId": "reports.getOffice365ActivationsUserCounts.21b3",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActivationsUserDetail()": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActivationsUserDetail",
        "operationId": "reports.getOffice365ActivationsUserDetail.1156",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActiveUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserCounts",
        "operationId": "reports.getOffice365ActiveUserCounts.c3b0",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActiveUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserDetail",
        "operationId": "reports.getOffice365ActiveUserDetail.3621",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ActiveUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ActiveUserDetail",
        "operationId": "reports.getOffice365ActiveUserDetail.7f57",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityCounts",
        "operationId": "reports.getOffice365GroupsActivityCounts.9333",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityDetail",
        "operationId": "reports.getOffice365GroupsActivityDetail.d699",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityDetail",
        "operationId": "reports.getOffice365GroupsActivityDetail.1b51",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityFileCounts",
        "operationId": "reports.getOffice365GroupsActivityFileCounts.7206",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityGroupCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityGroupCounts",
        "operationId": "reports.getOffice365GroupsActivityGroupCounts.f5de",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365GroupsActivityStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365GroupsActivityStorage",
        "operationId": "reports.getOffice365GroupsActivityStorage.a4d3",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOffice365ServicesUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOffice365ServicesUserCounts",
        "operationId": "reports.getOffice365ServicesUserCounts.0d23",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityFileCounts",
        "operationId": "reports.getOneDriveActivityFileCounts.c2dc",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserCounts",
        "operationId": "reports.getOneDriveActivityUserCounts.442b",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserDetail",
        "operationId": "reports.getOneDriveActivityUserDetail.57de",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveActivityUserDetail",
        "operationId": "reports.getOneDriveActivityUserDetail.20ae",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveUsageAccountCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountCounts",
        "operationId": "reports.getOneDriveUsageAccountCounts.801b",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveUsageAccountDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountDetail",
        "operationId": "reports.getOneDriveUsageAccountDetail.b461",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveUsageAccountDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageAccountDetail",
        "operationId": "reports.getOneDriveUsageAccountDetail.3f04",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveUsageFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageFileCounts",
        "operationId": "reports.getOneDriveUsageFileCounts.8444",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getOneDriveUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getOneDriveUsageStorage",
        "operationId": "reports.getOneDriveUsageStorage.c292",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointActivityFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityFileCounts",
        "operationId": "reports.getSharePointActivityFileCounts.b044",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointActivityPages(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityPages",
        "operationId": "reports.getSharePointActivityPages.73a2",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserCounts",
        "operationId": "reports.getSharePointActivityUserCounts.a723",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserDetail",
        "operationId": "reports.getSharePointActivityUserDetail.c908",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointActivityUserDetail",
        "operationId": "reports.getSharePointActivityUserDetail.9d39",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsageDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageDetail",
        "operationId": "reports.getSharePointSiteUsageDetail.9a98",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsageDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageDetail",
        "operationId": "reports.getSharePointSiteUsageDetail.bec0",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsageFileCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageFileCounts",
        "operationId": "reports.getSharePointSiteUsageFileCounts.b2bd",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsagePages(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsagePages",
        "operationId": "reports.getSharePointSiteUsagePages.ef52",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsageSiteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageSiteCounts",
        "operationId": "reports.getSharePointSiteUsageSiteCounts.1b68",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSharePointSiteUsageStorage(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSharePointSiteUsageStorage",
        "operationId": "reports.getSharePointSiteUsageStorage.4100",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityCounts",
        "operationId": "reports.getSkypeForBusinessActivityCounts.1cd1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserCounts",
        "operationId": "reports.getSkypeForBusinessActivityUserCounts.502a",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserDetail",
        "operationId": "reports.getSkypeForBusinessActivityUserDetail.de4b",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessActivityUserDetail",
        "operationId": "reports.getSkypeForBusinessActivityUserDetail.2a24",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageDistributionUserCounts",
        "operationId": "reports.getSkypeForBusinessDeviceUsageDistributionUserCounts.b288",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserCounts",
        "operationId": "reports.getSkypeForBusinessDeviceUsageUserCounts.afec",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserDetail",
        "operationId": "reports.getSkypeForBusinessDeviceUsageUserDetail.c31f",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessDeviceUsageUserDetail",
        "operationId": "reports.getSkypeForBusinessDeviceUsageUserDetail.e139",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessOrganizerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityCounts",
        "operationId": "reports.getSkypeForBusinessOrganizerActivityCounts.337a",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessOrganizerActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityMinuteCounts",
        "operationId": "reports.getSkypeForBusinessOrganizerActivityMinuteCounts.a6f3",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessOrganizerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessOrganizerActivityUserCounts",
        "operationId": "reports.getSkypeForBusinessOrganizerActivityUserCounts.61cb",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessParticipantActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityCounts",
        "operationId": "reports.getSkypeForBusinessParticipantActivityCounts.3f25",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessParticipantActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityMinuteCounts",
        "operationId": "reports.getSkypeForBusinessParticipantActivityMinuteCounts.19f1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessParticipantActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessParticipantActivityUserCounts",
        "operationId": "reports.getSkypeForBusinessParticipantActivityUserCounts.2fb8",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessPeerToPeerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityCounts",
        "operationId": "reports.getSkypeForBusinessPeerToPeerActivityCounts.4ba6",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessPeerToPeerActivityMinuteCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityMinuteCounts",
        "operationId": "reports.getSkypeForBusinessPeerToPeerActivityMinuteCounts.de62",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getSkypeForBusinessPeerToPeerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getSkypeForBusinessPeerToPeerActivityUserCounts",
        "operationId": "reports.getSkypeForBusinessPeerToPeerActivityUserCounts.5fbc",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageDistributionUserCounts",
        "operationId": "reports.getTeamsDeviceUsageDistributionUserCounts.91e1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserCounts",
        "operationId": "reports.getTeamsDeviceUsageUserCounts.c715",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserDetail",
        "operationId": "reports.getTeamsDeviceUsageUserDetail.43be",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsDeviceUsageUserDetail",
        "operationId": "reports.getTeamsDeviceUsageUserDetail.aab9",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsUserActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityCounts",
        "operationId": "reports.getTeamsUserActivityCounts.0201",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsUserActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserCounts",
        "operationId": "reports.getTeamsUserActivityUserCounts.fd77",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsUserActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserDetail",
        "operationId": "reports.getTeamsUserActivityUserDetail.3a37",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getTeamsUserActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getTeamsUserActivityUserDetail",
        "operationId": "reports.getTeamsUserActivityUserDetail.dd45",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityCounts",
        "operationId": "reports.getYammerActivityCounts.31c4",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerActivityUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserCounts",
        "operationId": "reports.getYammerActivityUserCounts.5f59",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerActivityUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserDetail",
        "operationId": "reports.getYammerActivityUserDetail.7d9d",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerActivityUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerActivityUserDetail",
        "operationId": "reports.getYammerActivityUserDetail.ca58",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerDeviceUsageDistributionUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageDistributionUserCounts",
        "operationId": "reports.getYammerDeviceUsageDistributionUserCounts.9d71",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerDeviceUsageUserCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserCounts",
        "operationId": "reports.getYammerDeviceUsageUserCounts.0624",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerDeviceUsageUserDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserDetail",
        "operationId": "reports.getYammerDeviceUsageUserDetail.c8b5",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerDeviceUsageUserDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerDeviceUsageUserDetail",
        "operationId": "reports.getYammerDeviceUsageUserDetail.1955",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerGroupsActivityCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityCounts",
        "operationId": "reports.getYammerGroupsActivityCounts.3fdb",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerGroupsActivityDetail(date={date})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityDetail",
        "operationId": "reports.getYammerGroupsActivityDetail.3ad3",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerGroupsActivityDetail(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityDetail",
        "operationId": "reports.getYammerGroupsActivityDetail.1de3",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/reports/getYammerGroupsActivityGroupCounts(period={period})": {
      "get": {
        "tags": [
          "reports.Functions"
        ],
        "summary": "Invoke function getYammerGroupsActivityGroupCounts",
        "operationId": "reports.getYammerGroupsActivityGroupCounts.61cb",
        "security": [
          {
            "Delegated (work or school account)": [
              "Reports.Read.All"
            ]
          },
          {
            "Application": [
              "Reports.Read.All"
            ]
          }
        ]
      }
    },
    "/schemaExtensions": {
      "get": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Get entities from schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.ListSchemaExtension"
      },
      "post": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Add new entity to schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.CreateSchemaExtension"
      }
    },
    "/schemaExtensions/{schemaExtension-id}": {
      "get": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Get entity from schemaExtensions by key",
        "operationId": "schemaExtensions.schemaExtension.GetSchemaExtension"
      },
      "patch": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Update entity in schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.UpdateSchemaExtension",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "schemaExtensions.schemaExtension"
        ],
        "summary": "Delete entity from schemaExtensions",
        "operationId": "schemaExtensions.schemaExtension.DeleteSchemaExtension",
        "security": [
          {
            "Delegated (work or school account)": [
              "Directory.AccessAsUser.All"
            ]
          }
        ]
      }
    },
    "/security": {
      "get": {
        "tags": [
          "security.security"
        ],
        "summary": "The **security** resource is available at the root of the graph.",
        "operationId": "security.security.GetSecurity"
      },
      "patch": {
        "tags": [
          "security.security"
        ],
        "summary": "Update security",
        "operationId": "security.security.UpdateSecurity"
      }
    },
    "/security/alerts": {
      "get": {
        "tags": [
          "security.alert"
        ],
        "summary": "Get alerts from security",
        "operationId": "security.ListAlerts"
      }
    },
    "/security/alerts/": {
      "get": {
        "tags": [
          "security.alert"
        ],
        "summary": "Get alerts from security",
        "operationId": "security.GetAlerts"
      }
    },
    "/shares": {
      "get": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Get entities from shares",
        "operationId": "shares.sharedDriveItem.ListSharedDriveItem",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Add new entity to shares",
        "operationId": "shares.sharedDriveItem.CreateSharedDriveItem"
      }
    },
    "/shares/{sharedDriveItem-id}": {
      "get": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Get entity from shares by key",
        "operationId": "shares.sharedDriveItem.GetSharedDriveItem",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.sharedDriveItem"
                }
              }
            },
            "links": {
              "driveItem": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              },
              "items": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              },
              "list": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              },
              "listItem": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              },
              "root": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              },
              "site": {
                "operationId": "shares.sharedDriveItem.GetSharedDriveItem"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Update entity in shares",
        "operationId": "shares.sharedDriveItem.UpdateSharedDriveItem"
      },
      "delete": {
        "tags": [
          "shares.sharedDriveItem"
        ],
        "summary": "Delete entity from shares",
        "operationId": "shares.sharedDriveItem.DeleteSharedDriveItem"
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get driveItem from shares",
        "operationId": "shares.GetDriveItem"
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "shares.driveItem.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "shares.driveItem.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.driveItem.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "shares.driveItem.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "shares.driveItem.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "shares.driveItem.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/driveItem/search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.driveItem.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get items from shares",
        "operationId": "shares.ListItems"
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get items from shares",
        "operationId": "shares.GetItems"
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "shares.items.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "shares.items.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.items.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "shares.items.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "shares.items.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "shares.items.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/items/{driveItem-id}/search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.items.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/list": {
      "get": {
        "tags": [
          "shares.list"
        ],
        "summary": "Get list from shares",
        "operationId": "shares.GetList"
      }
    },
    "/shares/{sharedDriveItem-id}/listItem": {
      "get": {
        "tags": [
          "shares.listItem"
        ],
        "summary": "Get listItem from shares",
        "operationId": "shares.GetListItem"
      }
    },
    "/shares/{sharedDriveItem-id}/root": {
      "get": {
        "tags": [
          "shares.driveItem"
        ],
        "summary": "Get root from shares",
        "operationId": "shares.GetRoot"
      }
    },
    "/shares/{sharedDriveItem-id}/root/copy": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Returns details about how to [monitor the progress](../../../concepts/long_running_actions_overview.md) of the copy, upon accepting the request.",
        "operationId": "shares.root.copy",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/createLink": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.\r\nThe sharing link is configured to be read-only and usable by anyone with the link.",
        "operationId": "shares.root.createLink",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/createUploadSession": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "Invoke action createUploadSession",
        "operationId": "shares.root.createUploadSession",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/delta()": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to establish your local state.",
        "operationId": "shares.root.delta.2209",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/delta(token={token})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Here is an example of how to call this API to update your local state.",
        "operationId": "shares.root.delta.cf70",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/invite": {
      "post": {
        "tags": [
          "shares.Actions"
        ],
        "summary": "This example sends a sharing invitation to a user with email address 'ryan@contoso.com' with a message about a file being collaborated on.\r\nThe invitation grants Ryan read-write access to the file.",
        "operationId": "shares.root.invite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.ReadWrite",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.ReadWrite.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/root/search(q={q})": {
      "get": {
        "tags": [
          "shares.Functions"
        ],
        "summary": "Invoke function search",
        "operationId": "shares.root.search.f2b1",
        "security": [
          {
            "Delegated (work or school account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Delegated (personal Microsoft account)": [
              "Files.Read",
              "Files.ReadWrite",
              "Files.Read.All",
              "Files.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Files.Read.All",
              "Files.ReadWrite.All",
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      }
    },
    "/shares/{sharedDriveItem-id}/site": {
      "get": {
        "tags": [
          "shares.site"
        ],
        "summary": "Get site from shares",
        "operationId": "shares.GetSite"
      }
    },
    "/sites": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get entities from sites",
        "operationId": "sites.site.ListSite",
        "security": [
          {
            "Delegated (work or school account)": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "sites.site"
        ],
        "summary": "Add new entity to sites",
        "operationId": "sites.site.CreateSite"
      }
    },
    "/sites/{site-id}": {
      "get": {
        "tags": [
          "sites.site"
        ],
        "summary": "Get entity from sites by key",
        "operationId": "sites.site.GetSite",
        "responses": {
          "200": {
            "description": "Retrieved entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.site"
                }
              }
            },
            "links": {
              "contentTypes": {
                "operationId": "sites.site.GetSite"
              },
              "drive": {
                "operationId": "sites.site.GetSite"
              },
              "drives": {
                "operationId": "sites.site.GetSite"
              },
              "items": {
                "operationId": "sites.site.GetSite"
              },
              "lists": {
                "operationId": "sites.site.GetSite"
              },
              "sites": {
                "operationId": "sites.site.GetSite"
              },
              "columns": {
                "operationId": "sites.site.GetSite"
              },
              "onenote": {
                "operationId": "sites.site.GetSite"
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "security": [
          {
            "Delegated (work or school account)": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          },
          {
            "Application": [
              "Sites.Read.All",
              "Sites.ReadWrite.All"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "sites.site"
        ],
        "summary": "Update entity in sites",
        "operationId": "sites.site.UpdateSite"
      },
      "delete": {
        "tags": [
          "sites.site"
        ],
        "summary": "Delete entity from sites",
        "operationId": "sites.site.DeleteSite"
      }
    },
    "/sites/{site-id}/columns": {
      "get": {
        "tags": [
          "sites.columnDefinition"
        ],
        "summary": "Get columns from sites",
        "operationId": "sites.ListColumns"
      }
    },
    "/sites/{site-id}/columns/{columnDefinition-id}": {
      "get": {
        "tags": [
          "sites.columnDefinition"
        ],
        "summary": "Get columns from sites",
        "operationId": "sites.GetColumns"
      }
    },
    "/sites/{site-id}/contentTypes": {
      "get": {
        "tags": [
          "sites.contentType"
        ],
        "summary": "Get contentTypes from sites",
        "operationId": "sites.ListContentTypes"
      }
    },
    "/sites/{site-id}/contentTypes/{contentType-id}": {
      "get": {
        "tags": [
          "sites.contentType"
        ],
        "summary": "Get contentTypes from sites",
        "operationId": "sites.GetContentTypes"
      }
    },
    "/sites/{site-id}/drive": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drive from sites",
        "operationId": "sites.GetDrive"
      }
    },
    "/sites/{site-id}/drives": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drives from sites",
        "operationId": "sites.ListDrives"
      }
    },
    "/sites/{site-id}/drives/{drive-id}": {
      "get": {
        "tags": [
          "sites.drive"
        ],
        "summary": "Get drives from sites",
        "operationId": "sites.GetDrives"
      }
    },
    "/sites/{site-id}/items": {
      "get": {
        "tags": [
          "sites.baseItem"
        ],
        "summary": "Get items from sites",
        "operationId": "sites.ListItems"
      }
    },
    "/sites/{site-id}/items/{baseItem-id}": {
      "get": {
        "tags": [
          "sites.baseItem"
        ],
        "summary": "Get items from sites",
        "operationId": "sites.GetItems"
      }
    },
[...]
